import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {initialState,act,clone,localDate,workoutProgress}=await import('../.sites-runtime/tests/completed-edit-domain.mjs');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});
const today=localDate(),timezone='Asia/Bangkok';let state=initialState(),revision=0;const actions=[],errors=[];
act(state,{type:'duplicateProgram',id:state.programs[0].id},today,timezone);const p=state.programs.at(-1);
act(state,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id,date:today},today,timezone);act(state,{type:'startWorkout',date:today},today,timezone);
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push(body.action.type);state=JSON.parse(JSON.stringify(act(clone(state),body.action,today,timezone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const workout=()=>page.locator('.workout'),weight=n=>workout().getByRole('spinbutton',{name:`Set ${n} weight`,exact:true}),reps=n=>workout().getByRole('spinbutton',{name:`Set ${n} reps`,exact:true}),check=n=>workout().getByRole('checkbox',{name:`Set ${n} completed`,exact:true});
async function saved(){await workout().getByText('Progress saved',{exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.workout fieldset:disabled'))}
async function complete(n){await weight(n).fill('70');await reps(n).fill('10');await check(n).click();await saved()}
async function toggle(n){await check(n).click();await saved()}
async function focusIs(n,field){await page.waitForFunction(label=>document.activeElement?.getAttribute('aria-label')===label,`Set ${n} ${field}`,{timeout:5000});assert.equal(await (field==='weight'?weight(n):reps(n)).evaluate(e=>document.activeElement===e),true,`focus stays in set ${n} ${field}`)}
async function current(n){assert.equal(await workout().locator('.setnext').getAttribute('data-set-id'),state.session.exercises[0].sets[n-1].id)}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded',timeout:60000});await workout().getByRole('heading',{name:'Bench Press',exact:true}).waitFor();
 await complete(1);const firstEnd=state.session.timerEnd;await weight(1).fill('75');await saved();assert.equal(state.session.exercises[0].sets[0].done,true);assert.equal(workoutProgress(state.session.exercises).done,1);assert.equal(state.session.timerEnd,firstEnd);await current(2);await focusIs(1,'weight');
 await complete(2);const end=state.session.timerEnd,source=clone(state.session.timerSource),other=clone(state.session.exercises[0].sets.slice(1)),plans=clone(state.programs);await weight(1).fill('72.5');await saved();await reps(1).fill('9');await saved();assert.equal(workoutProgress(state.session.exercises).done,2);assert.equal(state.session.timerEnd,end);assert.deepEqual(state.session.timerSource,source);assert.deepEqual(state.session.exercises[0].sets.slice(1),other);await current(3);await focusIs(1,'reps');console.log('PASS completed and older-set edits autosave without changing Done, progress, rest, other sets or editing focus');
 const posts=actions.length;await reps(1).fill('');await workout().getByText('Reps are required for a completed set.',{exact:true}).waitFor();await page.waitForTimeout(1100);assert.equal(actions.length,posts);assert.equal(await check(1).getAttribute('aria-checked'),'true');assert.equal(await reps(1).getAttribute('aria-invalid'),'true');assert.equal(state.session.exercises[0].sets[0].reps,9);assert.equal(await workout().locator('.badge').innerText(),'Unsaved changes');await current(3);
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.ok(await workout().evaluate(e=>e.scrollWidth<=e.clientWidth),`${width}px workout overflow`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px page overflow`);await page.screenshot({path:`.sites-runtime/completed-edit-invalid-${width}.png`,animations:'disabled'})}
 await reps(1).fill('11');await saved();assert.equal(state.session.exercises[0].sets[0].reps,11);assert.equal(state.session.timerEnd,end);await focusIs(1,'reps');console.log('PASS invalid completed values stay checked and local; inline errors fit 320/390px; valid correction resumes autosave');
 await reps(1).fill('');await workout().getByText('Reps are required for a completed set.',{exact:true}).waitFor();await toggle(1);assert.equal(state.session.exercises[0].sets[0].reps,null);assert.equal(state.session.exercises[0].sets[0].weight,72.5);assert.equal(workoutProgress(state.session.exercises).done,1);assert.equal(state.session.timerEnd,end);await current(3);
 await reps(1).fill('12');await saved();await toggle(1);assert.equal(workoutProgress(state.session.exercises).done,2);assert.equal(state.session.timerEnd,end);assert.deepEqual(state.session.timerSource,source);await current(3);console.log('PASS explicit older uncheck retains entered values, lowers progress and preserves newer rest; older recheck leaves timer and next set unchanged');
 await toggle(2);assert.equal(state.session.timerEnd,null);await toggle(1);assert.equal(state.session.timerEnd,null);await toggle(1);assert.ok(state.session.timerEnd);assert.equal(state.session.timerSource.setId,state.session.exercises[0].sets[0].id);await current(2);
 await page.reload();await workout().getByRole('heading',{name:'Bench Press',exact:true}).waitFor();assert.equal(await weight(1).inputValue(),'72.5');assert.equal(await reps(1).inputValue(),'12');assert.equal(await check(1).getAttribute('aria-checked'),'true');assert.deepEqual(state.programs,plans);assert.deepEqual(errors,[]);console.log('PASS source uncheck stops rest; sequential recheck restarts it; reload preserves saved values and plan; no browser errors');
}catch(e){console.log((await page.locator('body').innerText()).slice(-3000));throw e}finally{await browser.close()}
