import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {build} from 'esbuild';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/cycle-position-ui-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone}=await import('../.sites-runtime/tests/cycle-position-ui-domain.mjs'),today='2026-10-07',zone='Asia/Bangkok';let state=initialState(),revision=0;const actions=[],errors=[];
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844},timezoneId:zone});page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const {action}=route.request().postDataJSON();actions.push(action);state=JSON.parse(JSON.stringify(act(clone(state),action,today,zone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Choose a program',exact:true}).click();await page.getByRole('button',{name:'Choose preset',exact:true}).first().click();await page.getByLabel('Day 2 · Pull',{exact:true}).check();await page.getByRole('button',{name:'Start program',exact:true}).click();await page.getByRole('heading',{name:'Pull',exact:true}).waitFor();assert.equal(state.schedules[0].cycleState.index,1);assert.equal(state.logs.length,0);assert.equal(actions.filter(a=>a.type==='skipWorkout').length,0);
 await page.getByRole('button',{name:'Change workout',exact:true}).click();await page.getByLabel('Legs',{exact:true}).check();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('heading',{name:'Legs',exact:true}).waitFor();assert.equal(state.schedules[0].cycleState.index,2);assert.equal(state.schedules[0].skippedWorkouts.length,0);assert.equal(state.logs.length,0);
 await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'Legs',exact:true}).waitFor();await page.getByRole('button',{name:'Skip workout',exact:true}).click();await page.getByRole('alertdialog').getByRole('heading',{name:'Skip Legs?',exact:true}).waitFor();await page.getByRole('alertdialog').getByRole('button',{name:'Skip workout',exact:true}).click();await page.getByRole('heading',{name:'Push',exact:true}).waitFor();assert.equal(state.schedules[0].cycleState.index,0);assert.equal(state.schedules[0].skippedWorkouts.length,1);assert.equal(state.logs.length,0);assert.match(await page.locator('.week .istoday').getAttribute('aria-label'),/1 skipped workout/);assert.match(await page.locator('.skipped-workout-note').innerText(),/Skipped this cycle: Legs/);
 await page.getByRole('tab',{name:'Programs',exact:true}).click();const activeCard=page.locator('.programcard').filter({has:page.getByRole('heading',{name:'Push / Pull / Legs',exact:true})});await activeCard.getByRole('button',{name:'View program',exact:true}).click();await page.getByRole('button',{name:'Edit cycle',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Move Workout 1 down',exact:true}).isDisabled(),true);assert.match(await page.getByText(/Workout order cannot change until it is inactive/).innerText(),/Change workout/);await page.keyboard.press('Escape');
 await activeCard.getByRole('button',{name:'View program',exact:true}).click();await page.getByRole('button',{name:'Duplicate',exact:true}).click();await page.keyboard.press('Escape');const copyCard=page.locator('.programcard').filter({has:page.getByRole('heading',{name:'Push / Pull / Legs (copy)',exact:true})});await copyCard.getByRole('button',{name:'View program',exact:true}).click();await page.getByRole('button',{name:'Edit cycle',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Move Workout 1 down',exact:true}).isDisabled(),false);await page.getByRole('button',{name:'Move Workout 1 down',exact:true}).click();await page.getByRole('button',{name:'Save new version',exact:true}).click();assert.equal(state.programs.at(-1).versions.at(-1).days[0].name,'Pull');assert.equal(state.programs.find(p=>p.id===state.schedules[0].applications[0].programId).versions.at(-1).days[0].name,'Push');
 await page.getByRole('tab',{name:'Schedule',exact:true}).click();
 await page.getByRole('button',{name:'Start workout · Push',exact:true}).click();await page.locator('.workout').waitFor();assert.equal(await page.getByRole('button',{name:'Change workout',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Skip workout',exact:true}).count(),0);assert.equal(state.schedules[0].skippedWorkouts.length,1);assert.deepEqual(errors,[]);
 console.log('PASS initial Start from Pull; Change workout persists without history/skip; Skip confirms, advances and persists its marker; cycle actions disappear during an active session.');
}finally{await browser.close()}
