import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/cycle-position-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,withPresets,nextProgramWorkout,currentProgram}=await import('../.sites-runtime/tests/cycle-position-domain.mjs');const today='2026-10-07',zone='Asia/Bangkok';
function programFixture(){const s=initialState();act(s,{type:'duplicateProgram',id:s.programs[0].id},today,zone);return s}
function fixture(){const s=programFixture(),p=s.programs.at(-1);act(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id},today,zone);return s}
const apply=(s,a)=>act(s,a,today,zone);
test('initial position starts at chosen workout, advances through the end then wraps without synthetic history',()=>{const s=programFixture(),programs=clone(s.programs);apply(s,{type:'createSchedule',programId:s.programs.at(-1).id,versionId:s.programs.at(-1).versions[0].id,startIndex:1});assert.equal(nextProgramWorkout(s,today).day.name,'Pull');assert.equal(s.logs.length,0);for(const name of ['Pull','Legs','Push']){assert.equal(nextProgramWorkout(s,today).day.name,name);apply(s,{type:'startWorkout',date:today});apply(s,{type:'finishWorkout',confirmIncomplete:true})}assert.equal(nextProgramWorkout(s,today).day.name,'Pull');assert.equal(currentProgram(s,today).cursor.cycleNumber,2);assert.deepEqual(s.programs,programs)});
test('Change workout persists the active position without skip, log or program mutation',()=>{const s=fixture(),schedule=s.schedules[0],programs=clone(s.programs),applications=clone(schedule.applications);apply(s,{type:'changeWorkout',index:2});assert.equal(nextProgramWorkout(s,today).day.name,'Legs');assert.equal(schedule.cycleState.index,2);assert.deepEqual(schedule.applications,applications);assert.deepEqual(schedule.skippedWorkouts||[],[]);assert.deepEqual(s.logs,[]);assert.deepEqual(s.programs,programs);assert.equal(nextProgramWorkout(withPresets(clone(s)),today).day.name,'Legs')});
test('Change workout cannot replace a running session and cannot select an already skipped workout',()=>{const s=fixture(),sessionAction={type:'startWorkout',date:today};apply(s,sessionAction);Object.assign(s.session.exercises[0].sets[0],{reps:8,weight:20});const before=clone(s);assert.throws(()=>apply(s,{type:'changeWorkout',index:1}),/Finish or discard/);assert.deepEqual(s,before);const t=fixture();apply(t,{type:'skipWorkout',confirmed:true});assert.equal(nextProgramWorkout(t,today).day.name,'Pull');assert.throws(()=>apply(t,{type:'changeWorkout',index:0}),/already skipped/)});
test('Skip requires confirmation, persists its occurrence, and advances exactly once without History',()=>{const s=fixture(),schedule=s.schedules[0],programs=clone(s.programs);assert.throws(()=>apply(s,{type:'skipWorkout'}),/Confirm/);const original=nextProgramWorkout(s,today);apply(s,{type:'skipWorkout',confirmed:true});assert.equal(schedule.skippedWorkouts.length,1);assert.deepEqual(schedule.skippedWorkouts[0].occurrence,original);assert.equal(nextProgramWorkout(s,today).day.name,'Pull');assert.equal(s.logs.length,0);assert.deepEqual(s.programs,programs);assert.equal(apply(s,{type:'skipWorkout',confirmed:true}).schedules[0].skippedWorkouts.length,2);const reloaded=withPresets(clone(s));assert.equal(reloaded.schedules[0].skippedWorkouts.length,2);assert.equal(nextProgramWorkout(reloaded,today).day.name,'Legs')});
test('queued version preserves a chosen next-cycle start position',()=>{const s=fixture(),p=s.programs.at(-1),days=clone(p.versions[0].days);days[0].name='Fresh Push';apply(s,{type:'saveProgram',id:p.id,name:p.name,description:p.description,days});const version=p.versions.at(-1);apply(s,{type:'applyVersion',programId:p.id,versionId:version.id,mode:'AFTER_CYCLE',startIndex:2});for(const name of ['Push','Pull','Legs']){assert.equal(nextProgramWorkout(s,today).day.name,name);apply(s,{type:'startWorkout',date:today});apply(s,{type:'finishWorkout',confirmIncomplete:true})}assert.equal(nextProgramWorkout(s,today).day.name,'Legs');assert.equal(nextProgramWorkout(s,today).versionNumber,2)});
test('inactive Program reorder creates a new version and active Program edits are blocked',()=>{const s=programFixture(),p=s.programs.at(-1),original=clone(p.versions[0]),days=clone(p.versions[0].days);[days[0],days[1]]=[days[1],days[0]];apply(s,{type:'saveProgram',id:p.id,name:p.name,description:p.description,days});assert.deepEqual(p.versions[0],original);assert.equal(p.versions.at(-1).days[0].name,'Pull');const other=fixture(),active=other.programs.at(-1),activeDays=clone(active.versions[0].days),before=clone(other);[activeDays[0],activeDays[1]]=[activeDays[1],activeDays[0]];assert.throws(()=>apply(other,{type:'saveProgram',id:active.id,name:active.name,description:active.description,days:activeDays}),/order cannot be changed/);assert.deepEqual(other,before);});
