import assert from 'node:assert/strict';
import {test} from 'node:test';
import {build} from 'esbuild';
import {mkdir} from 'node:fs/promises';
await mkdir('.sites-runtime/tests',{recursive:true});
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';export * from './lib/workout-rules';export * from './lib/schedule-review';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/finish-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,plannedWorkStatus,finishWorkoutMessage,nextScheduledWorkout,addDays,withPresets,projection}=await import('../.sites-runtime/tests/finish-domain.mjs');
const today='2026-10-07',zone='Asia/Bangkok',action=(s,a)=>act(s,a,today,zone);
function fixture(completed,skipped,pending){const s=initialState();const plan=(exerciseId,sets)=>({id:exerciseId,exerciseId,name:exerciseId,sets,repMin:8,repMax:12,rest:90});action(s,{type:'saveProgram',name:'Finish QA',days:[{type:'WORKOUT',name:'Push',exercises:[[completed,'bench'],[skipped,'row'],[pending,'squat']].filter(([n])=>n>0).map(([n,id])=>plan(id,n))},{type:'WORKOUT',name:'Pull',exercises:[plan('row',3)]},{type:'REST',name:'Rest',exercises:[]}]});const p=s.programs.at(-1);action(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id,date:today});action(s,{type:'startWorkout',date:today});for(const e of s.session.exercises){if(e.exerciseId==='bench')for(const set of e.sets)Object.assign(set,{weight:70,reps:10,done:true});if(e.exerciseId==='row'){e.skipped=true;for(const set of e.sets)set.skipped=true}}return s}

test('counts completed, skipped and genuinely pending planned sets separately',()=>{for(const [done,skipped,pending]of [[8,2,0],[8,2,2],[8,0,4],[0,12,0],[12,0,0]])assert.deepEqual(plannedWorkStatus(fixture(done,skipped,pending).session.exercises),{total:done+skipped+pending,completed:done,skipped,pending});assert.equal(finishWorkoutMessage(plannedWorkStatus(fixture(8,2,2).session.exercises)),'8 of 12 planned sets completed · 2 skipped · 2 still pending.');assert.equal(finishWorkoutMessage(plannedWorkStatus(fixture(8,0,4).session.exercises)),'You completed 8 of 12 planned sets. 4 sets are still pending.');assert.match(finishWorkoutMessage(plannedWorkStatus(fixture(8,0,1).session.exercises)),/1 set is still pending/)});
test('extra sets do not trigger the planned-work prompt and legacy exercise skips stay intentional',()=>{const s=fixture(8,2,0);action(s,{type:'addSet',exerciseId:s.session.exercises[0].id});assert.equal(plannedWorkStatus(s.session.exercises).pending,0);const skipped=s.session.exercises[1];for(const set of skipped.sets)delete set.skipped;withPresets(s);assert.equal(plannedWorkStatus(s.session.exercises).skipped,2);action(s,{type:'finishWorkout'});assert.equal(s.logs[0].status,'PARTIALLY_COMPLETED')});
test('fully handled sets finish directly, preserving skips and normal completion status',()=>{for(const [done,skipped,status]of [[8,2,'PARTIALLY_COMPLETED'],[12,0,'COMPLETED'],[0,12,'PARTIALLY_COMPLETED']]){const s=fixture(done,skipped,0),before=clone(s.session.exercises);action(s,{type:'finishWorkout'});assert.equal(s.session,null);assert.equal(s.logs[0].status,status);assert.deepEqual(s.logs[0].exercises,before)}});
test('pending sets require explicit finish; committed result retains incomplete entries and advances to the next cycle workout',()=>{const s=fixture(8,2,2),pending=s.session.exercises.at(-1).sets[0];Object.assign(pending,{weight:32,reps:9});s.session.notes='Keep my notes';s.session.timerEnd=Date.now()+60000;const before=clone(s);assert.throws(()=>action(s,{type:'finishWorkout'}),e=>e.code==='INCOMPLETE');assert.deepEqual(s,before);action(s,{type:'finishWorkout',confirmIncomplete:true});assert.deepEqual(s.logs[0].exercises,before.session.exercises);assert.equal(s.logs[0].notes,'Keep my notes');assert.equal(s.logs[0].timerEnd,null);assert.equal(s.logs[0].status,'PARTIALLY_COMPLETED');assert.deepEqual(s.programs,before.programs);assert.equal(s.schedules[0].cycleState.index,1);assert.deepEqual(s.schedules[0].applications,before.schedules[0].applications);assert.equal(nextScheduledWorkout(s,today).date,today);assert.equal(nextScheduledWorkout(s,today).day.name,'Pull')});
test('unscheduled finish still requires a performed set',()=>{const s=initialState();action(s,{type:'startWorkout',date:today,unscheduled:true});assert.throws(()=>action(s,{type:'finishWorkout'}),/at least one set/);action(s,{type:'addExercise',exerciseId:'bench'});Object.assign(s.session.exercises[0].sets[0],{weight:40,reps:8,done:true});assert.deepEqual(plannedWorkStatus(s.session.exercises),{total:0,completed:0,skipped:0,pending:0});action(s,{type:'finishWorkout'});assert.equal(s.logs[0].status,'UNSCHEDULED')});

test('unchecking a completed set after a partial skip returns planned work to pending',()=>{const s=fixture(8,2,0),e=s.session.exercises[0];e.skipped=true;e.sets[0].done=false;e.sets[0].skipped=false;assert.equal(plannedWorkStatus(s.session.exercises).pending,1);assert.throws(()=>action(s,{type:'finishWorkout'}),e=>e.code==='INCOMPLETE')});
test('timer adjustments preserve one rest period and never produce negative remaining time',()=>{const s=fixture(8,2,0);action(s,{type:'timer',seconds:60});const id=s.session.timerId,end=s.session.timerEnd;action(s,{type:'timer',adjust:15});assert.equal(s.session.timerEnd,end+15000);action(s,{type:'timer',adjust:-15});assert.equal(s.session.timerEnd,end);assert.equal(s.session.timerId,id);action(s,{type:'timer',seconds:1});action(s,{type:'timer',adjust:-15});assert.ok(Math.abs(s.session.timerEnd-Date.now())<100);action(s,{type:'timer',seconds:null});assert.equal(s.session.timerEnd,null);assert.equal(s.session.timerId,null);assert.throws(()=>action(s,{type:'timer',adjust:15}),/Start rest/)});
test('discard deletes only the in-progress session and does not advance its schedule',()=>{const s=fixture(8,2,2),before=clone(s);action(s,{type:'addSet',exerciseId:s.session.exercises[0].id});action(s,{type:'addExercise',exerciseId:'curl'});assert.throws(()=>action(s,{type:'discardWorkout'}),/Confirm/);action(s,{type:'discardWorkout',confirmed:true});assert.equal(s.session,null);assert.deepEqual(s.logs,before.logs);assert.deepEqual(s.programs,before.programs);assert.deepEqual(s.schedules,before.schedules);assert.deepEqual(projection(s,today),projection(before,today))});
