import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {build} from 'esbuild';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/finish-ui-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,localDate}=await import('../.sites-runtime/tests/finish-ui-domain.mjs'),today=localDate(),zone='Asia/Bangkok';
function fixture(completed,skipped,pending){const s=initialState(),plan=(id,sets)=>({id,exerciseId:id,name:id,sets,repMin:8,repMax:12,rest:90});act(s,{type:'saveProgram',name:'Finish QA',days:[{type:'WORKOUT',name:'Push',exercises:[[completed,'bench'],[skipped,'row'],[pending,'squat']].filter(([n])=>n>0).map(([n,id])=>plan(id,n))},{type:'WORKOUT',name:'Pull',exercises:[plan('row',3)]},{type:'REST',name:'Rest',exercises:[]}]},today,zone);const p=s.programs.at(-1);act(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id,date:today},today,zone);act(s,{type:'startWorkout',date:today},today,zone);for(const e of s.session.exercises){if(e.exerciseId==='bench')for(const set of e.sets)Object.assign(set,{weight:70,reps:10,done:true});if(e.exerciseId==='row'){e.skipped=true;for(const set of e.sets)set.skipped=true}}return s}
let state=fixture(8,2,2),revision=0,failFinish=false;const actions=[],errors=[];
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:982,height:871},colorScheme:'light'});page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const {action}=route.request().postDataJSON();actions.push(action);if(action.type==='finishWorkout'&&failFinish){await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Try again'})});return}state=JSON.parse(JSON.stringify(act(clone(state),action,today,zone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const workout=()=>page.locator('.workout'),dialog=()=>page.getByRole('alertdialog'),finish=()=>workout().getByRole('button',{name:'Finish workout',exact:true});
async function load(){await page.reload();await workout().getByRole('heading',{name:'Push',exact:true}).waitFor()}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await workout().getByRole('heading',{name:'Push',exact:true}).waitFor();await workout().locator('.exercise-nav').getByRole('button',{name:/Back Squat/}).click();await workout().getByRole('spinbutton',{name:'Set 1 weight',exact:true}).fill('32');await workout().getByRole('spinbutton',{name:'Set 1 reps',exact:true}).fill('9');await workout().getByRole('textbox',{name:'Workout notes',exact:true}).fill('Preserve these entries');await finish().click();await dialog().getByRole('heading',{name:'Finish workout?',exact:true}).waitFor();assert.equal(await dialog().getByText('8 of 12 planned sets completed · 2 skipped · 2 still pending.',{exact:true}).count(),1);assert.equal(await dialog().getByRole('button',{name:'Keep training',exact:true}).evaluate(e=>e===document.activeElement),true);assert.equal(await dialog().locator('svg').count(),0);assert.equal(await dialog().getByRole('button',{name:'Confirm',exact:true}).count(),0);const saved=clone(state.session),selected=await workout().locator('.exercise-nav .selected').innerText();
 for(const width of [320,390,668,982]){await page.setViewportSize({width,height:871});assert.equal(await dialog().evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===390||width===982)await page.screenshot({path:`.sites-runtime/finish-workout-${width}.png`,animations:'disabled'})}
 await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:'.sites-runtime/finish-workout-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});await dialog().getByRole('button',{name:'Keep training',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.deepEqual(state.session,saved);assert.equal(await workout().locator('.exercise-nav .selected').innerText(),selected);assert.equal(await workout().getByRole('spinbutton',{name:'Set 1 weight',exact:true}).inputValue(),'32');assert.equal(await workout().getByRole('textbox',{name:'Workout notes',exact:true}).inputValue(),'Preserve these entries');assert.equal(actions.filter(a=>a.type==='finishWorkout').length,0);
 await finish().click();await dialog().waitFor();failFinish=true;await dialog().getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByText('Try again',{exact:true}).waitFor();assert.deepEqual(state.session,saved);assert.equal(state.logs.length,0);assert.equal(await dialog().isVisible(),true);failFinish=false;await dialog().getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('heading',{name:'Workout Summary',exact:true}).waitFor();assert.equal(state.session,null);assert.deepEqual(state.logs[0].exercises,saved.exercises);assert.equal(state.logs[0].notes,saved.notes);assert.equal(state.logs[0].status,'PARTIALLY_COMPLETED');assert.equal(await page.getByRole('progressbar',{name:'Planned sets completed',exact:true}).getAttribute('aria-valuenow'),'67');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('heading',{name:'Workout saved',exact:true}).waitFor();assert.match(await page.locator('.schedule-acknowledgement').innerText(),/Workout 2 of 2 · Pull/);assert.equal(await page.locator('.mainnav').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(255, 255, 255, 0.72)');await page.emulateMedia({colorScheme:'dark'});assert.equal(await page.locator('.mainnav').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(15, 23, 42, 0.96)');await page.emulateMedia({colorScheme:'light'});
 for(const [completed,skipped,pending,body]of [[8,0,4,'You completed 8 of 12 planned sets. 4 sets are still pending.'],[8,0,1,'You completed 8 of 9 planned sets. 1 set is still pending.']]){state=fixture(completed,skipped,pending);revision++;await load();await finish().click();await dialog().getByText(body,{exact:true}).waitFor();await dialog().getByRole('button',{name:'Keep training',exact:true}).click();await dialog().waitFor({state:'hidden'})}
 for(const [completed,skipped]of [[8,2],[12,0],[0,12]]){state=fixture(completed,skipped,0);revision++;await load();await finish().click();await page.getByRole('heading',{name:'Workout Summary',exact:true}).waitFor();assert.equal(await dialog().count(),0);assert.equal(state.session,null);assert.equal(state.logs.length,1)}
 state=fixture(8,0,4);revision++;await load();await workout().getByRole('button',{name:'Discard workout',exact:true}).click();await dialog().getByRole('button',{name:'Keep workout',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.ok(state.session);assert.deepEqual(errors,[]);console.log('PASS exact dynamic copy, Keep training preserves draft/navigation, finish retry and summary, completion-driven next workout, 8+2 skipped direct finish, completed/all-skipped paths, mobile/dark layout, navigation opacity and safe discard labels.');
}finally{await browser.close()}
