import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const require=createRequire(import.meta.url),pw=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/history-glass-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone}=await import('../.sites-runtime/tests/history-glass-domain.mjs'),today='2026-10-07',zone='Asia/Bangkok';
let state=initialState(),revision=0,failDelete=false;
act(state,{type:'duplicateProgram',id:state.programs[0].id},today,zone);const program=state.programs.at(-1);
act(state,{type:'createSchedule',programId:program.id,versionId:program.versions[0].id},today,zone);
act(state,{type:'startWorkout',date:today},today,zone);
for(const e of state.session.exercises)for(const set of e.sets)Object.assign(set,{done:true,reps:10,weight:20});
state.session.exercises[0].sets.push({id:'extra-history',planned:false,done:true,reps:10,weight:20});
state.session.startedAt='2026-10-07T05:00:00Z';act(state,{type:'finishWorkout'},today,zone);const base=clone(state.logs[0]);
state.logs=Array.from({length:4},(_,i)=>({...clone(base),id:`history-${i}`,date:i===3?'2026-10-06':today,startedAt:`2026-10-07T0${5-i}:00:00Z`,finishedAt:`2026-10-07T0${5-i}:30:00Z`}));
Object.assign(state.logs[1],{name:'Unscheduled Workout',occurrence:null,status:'UNSCHEDULED'});
state.logs[2].name='A long workout title that should remain readable on narrow mobile screens';state.logs[2].status='PARTIALLY_COMPLETED';state.logs[2].exercises[0].sets[0].done=false;
state.logs[3].status='PARTIALLY_COMPLETED';for(const e of state.logs[3].exercises)for(const set of e.sets)Object.assign(set,{done:false,skipped:true});
const before=clone(state),posts=[],errors=[],browserName=process.env.TEST_BROWSER||'chromium';
const browser=await pw[browserName].launch({headless:true,...(browserName==='chromium'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});
const page=await browser.newPage({viewport:{width:390,height:844},timezoneId:zone,colorScheme:'light'});
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{if(route.request().method()==='POST'){const {action}=route.request().postDataJSON();posts.push(action);if(action.type==='deleteLog'&&failDelete){failDelete=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Please retry deletion.'})});return}state=act(clone(state),action,today,zone);revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})});
async function history(){await page.evaluate(()=>dispatchEvent(new WheelEvent('wheel',{deltaY:4})));await page.getByRole('tab',{name:'History',exact:true}).click();await page.locator('.historysummary').waitFor()}
try{
 await page.clock.install({time:new Date('2026-10-07T07:00:00Z')});await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.locator('.calendar').waitFor();await history();await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.locator('.historysummary b').first().innerText(),'4');assert.equal(await page.locator('.historysummary b').first().evaluate(e=>getComputedStyle(e).fontWeight),'800');
 assert.equal(await page.locator('.historylist .history-workout-card').count(),4);assert.equal(await page.locator('.historylist .history-status-dot').count(),1);
 for(const width of [374,375,390,430,982]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const card of await page.locator('.historylist .history-workout-card').all()){assert.equal(await card.evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.equal(await card.evaluate(e=>getComputedStyle(e).borderRadius),'20px');assert.equal(await card.evaluate(e=>getComputedStyle(e).backdropFilter),'blur(20px)');const title=card.locator('strong');assert.equal(await title.evaluate(e=>e.scrollWidth>e.clientWidth),false)}await page.screenshot({path:`.sites-runtime/history-glass-${browserName}-${width}.png`,fullPage:true,animations:'disabled'})}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Search and filter',exact:true}).click();await page.getByLabel('Search workout history').fill('Unscheduled');assert.equal(await page.locator('.historylist .history-workout-card').count(),1);await page.getByLabel('Search workout history').fill('no such workout');await page.getByText('No workouts match your filters.',{exact:true}).waitFor();await page.getByLabel('Search workout history').fill('');
 await page.getByLabel('Completion filter',{exact:true}).click();await page.getByRole('option',{name:'Completed',exact:true}).click();assert.equal(await page.locator('.historylist .history-workout-card').count(),1);await page.getByLabel('Completion filter',{exact:true}).click();await page.getByRole('option',{name:'All workouts',exact:true}).click();
 await page.getByLabel('From',{exact:true}).fill(today);assert.equal(await page.locator('.historylist .history-workout-card').count(),3);await page.getByLabel('From',{exact:true}).fill('');await page.getByRole('button',{name:'Search and filter',exact:true}).click();
 await page.locator('[data-history-id="history-0"]').click();await page.getByRole('region',{name:'Workout history detail'}).waitFor();await page.getByRole('button',{name:'View / edit workout log',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Back to history',exact:true}).click();await page.locator('.historysummary').waitFor();assert.equal(posts.length,0);assert.deepEqual(state,before);
 await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});assert.equal(await page.locator('.history-status-dot').evaluate(e=>getComputedStyle(e).animationName),'none');await page.screenshot({path:`.sites-runtime/history-glass-${browserName}-dark.png`,fullPage:true,animations:'disabled'});await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});
 for(const tab of ['Schedule','Programs','Settings','History']){await page.evaluate(()=>dispatchEvent(new WheelEvent('wheel',{deltaY:4})));await page.getByRole('tab',{name:tab,exact:true}).click();assert.equal(await page.locator('[aria-label="Personal workspace"]').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}
 const dialog=()=>page.getByRole('alertdialog');
 await page.getByRole('button',{name:'Start unscheduled workout',exact:true}).click();await dialog().getByRole('heading',{name:'Start unscheduled workout?',exact:true}).waitFor();assert.equal(state.session,null);assert.equal(posts.length,0);await dialog().getByRole('button',{name:'Keep browsing',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.deepEqual(state,before);
 await page.getByRole('button',{name:'Start unscheduled workout',exact:true}).click();await dialog().getByRole('button',{name:'Start workout',exact:true}).click();await page.locator('.workout').waitFor();assert.ok(state.session);assert.equal(state.logs.length,4);assert.deepEqual(state.schedules,before.schedules);await history();await page.locator('.history-tools').getByRole('button',{name:'Resume workout',exact:true}).click();await page.locator('.workout').waitFor();assert.equal(posts.filter(a=>a.type==='startWorkout').length,1);
 const keep=clone(state);await history();await page.locator('[data-history-id="history-0"]').click();await page.getByRole('button',{name:'Delete workout',exact:true}).click();await dialog().getByRole('heading',{name:'Delete workout?',exact:true}).waitFor();await dialog().getByRole('button',{name:'Keep workout',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.deepEqual(state,keep);assert.equal(posts.filter(a=>a.type==='deleteLog').length,0);
 await page.getByRole('button',{name:'Delete workout',exact:true}).click();failDelete=true;await dialog().getByRole('button',{name:'Delete workout',exact:true}).click();await page.getByText('Please retry deletion.',{exact:true}).waitFor();assert.deepEqual(state,keep);await dialog().getByRole('button',{name:'Delete workout',exact:true}).click();await page.locator('.historysummary').waitFor();assert.equal(await page.locator('.historysummary b').first().innerText(),'3');assert.equal(state.logs.some(l=>l.id==='history-0'),false);
 await page.locator('[data-history-id="history-1"]').click();await page.getByRole('button',{name:'Delete workout',exact:true}).click();await dialog().getByRole('button',{name:'Delete workout',exact:true}).click();await page.locator('.historysummary').waitFor();assert.equal(await page.locator('.historysummary b').first().innerText(),'2');assert.deepEqual(state.schedules,keep.schedules);assert.deepEqual(state.programs,keep.programs);assert.deepEqual(state.session,keep.session);
 await page.reload({waitUntil:'domcontentloaded'});await history();assert.equal(await page.locator('.historylist .history-workout-card').count(),2);assert.equal(await page.locator('[data-history-id="history-0"],[data-history-id="history-1"]').count(),0);assert.deepEqual(errors,[]);
 console.log(`PASS ${browserName}: History glass at 375/390/430/982px; completed/partial/skipped/unscheduled and extra work; filters/search/date and detail/edit navigation without writes; quick add confirms or resumes; cancelled/failed deletion retains data, retry deletes scheduled/unscheduled logs across reload without cycle/session changes; dark/reduced motion.`);
}finally{await browser.close()}
