import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {build} from 'esbuild';
const require=createRequire(import.meta.url),pw=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/mobile-schedule-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone}=await import('../.sites-runtime/tests/mobile-schedule-domain.mjs'),today='2026-10-07',zone='Asia/Bangkok';
function fixture(count){const s=initialState();act(s,{type:'duplicateProgram',id:s.programs[0].id},today,zone);const p=s.programs.at(-1);act(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id},today,zone);act(s,{type:'startWorkout',date:today},today,zone);Object.assign(s.session.exercises[0].sets[0],{done:true,weight:20,reps:8});act(s,{type:'finishWorkout',confirmIncomplete:true},today,zone);const log=clone(s.logs[0]);s.logs=Array.from({length:count},(_,i)=>({...clone(log),id:`mobile-log-${i}`,date:i===count-1?'2026-10-06':today,finishedAt:new Date(Date.parse('2026-10-07T05:00:00Z')-i*60000).toISOString()}));return s}
const browserName=process.env.TEST_BROWSER||'chromium',browser=await pw[browserName].launch({headless:true,...(browserName==='chromium'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});
const page=await browser.newPage({viewport:{width:390,height:844},timezoneId:zone,isMobile:true,hasTouch:true});page.setDefaultTimeout(10000);const errors=[],posts=[];let state=fixture(7);page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async r=>{if(r.request().method()==='POST')posts.push(r.request().postDataJSON());await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision:0})})});
const dock=()=>page.locator('.mainnav');async function clock(ms){await page.clock.runFor(ms)}async function reveal(){await page.evaluate(()=>window.dispatchEvent(new WheelEvent('wheel',{deltaY:4})));await clock(300)}
async function visible(expected){assert.equal(await dock().getAttribute('data-dock-hidden'),expected?'false':'true');assert.equal(await dock().evaluate(e=>e.inert),!expected)}
try{
 await page.clock.install({time:new Date('2026-10-07T05:00:00Z')});await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.locator('.calendar').waitFor();await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.evaluate(()=>document.fonts.check('500 16px "Plus Jakarta Sans"')),true);assert.match(await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily),/Plus Jakarta Sans/);assert.equal(await page.locator('.footnote').first().evaluate(e=>getComputedStyle(e).fontWeight),'500');
 assert.equal(await page.locator('.pagehead h1').evaluate(e=>getComputedStyle(e).fontWeight),'700');await visible(true);const geometry=await page.locator('.calendar').evaluate(e=>({top:e.getBoundingClientRect().top+scrollY,height:document.documentElement.scrollHeight}));await clock(2400);await visible(false);assert.deepEqual(await page.locator('.calendar').evaluate(e=>({top:e.getBoundingClientRect().top+scrollY,height:document.documentElement.scrollHeight})),geometry);
 await page.evaluate(()=>{scrollBy(0,120);dispatchEvent(new Event('scroll'))});await clock(100);await visible(true);await page.evaluate(()=>{scrollBy(0,-70);dispatchEvent(new Event('scroll'))});await clock(100);await visible(true);await clock(1800);await visible(false);
 // Reveal on a small edge gesture, then hold across a tab change.
 await page.dispatchEvent('body','pointerdown',{pointerType:'touch',clientY:830});await clock(100);await visible(true);await page.dispatchEvent('body','pointerup',{pointerType:'touch'});await clock(100);
 const programs=page.getByRole('tab',{name:'Programs',exact:true});await programs.scrollIntoViewIfNeeded();const box=await programs.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await clock(3500);await visible(true);await page.mouse.up();await clock(1800);await visible(false);
 await reveal();await page.getByRole('tab',{name:'Schedule',exact:true}).click();await clock(100);await visible(true);
 const original=clone(state);await page.locator('.week button').filter({has:page.locator('b').filter({hasText:/^6$/})}).click();await page.getByRole('button',{name:'Back to Today',exact:true}).waitFor();assert.equal(await page.locator('.week .selected b').innerText(),'6');assert.equal(await page.locator('.week .istoday').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('.week .istoday .daymark.complete').count(),1);assert.match(await page.locator('.week .istoday').evaluate(e=>getComputedStyle(e).backgroundImage),/^none$/);await page.locator('.recorded-workouts').getByRole('heading',{name:'Tuesday, October 6',exact:true}).waitFor();await clock(4000);assert.equal(await page.locator('.week .selected b').innerText(),'6');assert.deepEqual(state,original);
 for(const count of [1,2,7]){state=fixture(count);await page.reload();await page.locator('.calendar').waitFor();assert.equal(await page.locator('.recent-workouts-list .recentlog').count(),count);for(const width of [375,390,430]){await page.setViewportSize({width,height:844});await reveal();await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await clock(100);const last=page.locator('.recent-workouts-list .recentlog').last(),b=await last.boundingBox(),nav=await dock().boundingBox();assert.ok(b.y+b.height<=nav.y-8,`${browserName} ${width}px/${count} cards: last card clears dock`);assert.equal(await last.evaluate(e=>{const b=e.getBoundingClientRect();const hit=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return e===hit||e.contains(hit)}),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const badge of await page.locator('.day-workout-count').all())assert.equal(await badge.evaluate(e=>e.scrollWidth>e.clientWidth),false);const top=await page.locator('.recent-workouts-list').evaluate(e=>e.getBoundingClientRect().top+scrollY);await page.setViewportSize({width,height:724});await clock(100);assert.equal(await page.locator('.recent-workouts-list').evaluate(e=>e.getBoundingClientRect().top+scrollY),top);assert.ok((await dock().boundingBox()).y+(await dock().boundingBox()).height<=724);await page.setViewportSize({width,height:844})}}
 const beforeReturn=clone(state);await page.evaluate(()=>scrollTo(0,0));await page.locator('.week button').filter({has:page.locator('b').filter({hasText:/^6$/})}).click();await page.getByRole('button',{name:'Back to Today',exact:true}).click();assert.equal(await page.locator('.week .selected b').innerText(),'7');assert.equal(await page.getByRole('button',{name:'Back to Today',exact:true}).count(),0);assert.equal(posts.length,0);assert.deepEqual(state,beforeReturn);
 // Explicitly verify navigation changes never mutated the original fixture's program or records.
 assert.deepEqual(errors,[]);await page.screenshot({path:`.sites-runtime/mobile-schedule-${browserName}.png`,fullPage:true,animations:'disabled'});console.log(`PASS ${browserName}: local Jakarta font; initial/idle/show-up/show-down/hold/tab reveal; no nav layout shift; selected vs Today/complete; Back to Today without API writes; all 1/2/7 recent cards reachable at 375/390/430px and changing viewport heights.`);
}finally{await browser.close()}
