import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {initialState,act,clone,localDate,plannedSets,displayWeight}=await import('../.sites-runtime/tests/per-set-domain.mjs');
const today=localDate(),timezone='Asia/Bangkok';let state=initialState(),revision=0;const actions=[],errors=[];
state.programs.push({id:'legacy',name:'Legacy UI',description:'Old scalar prescriptions',archived:false,versions:[{id:'legacy-v1',number:1,createdAt:'2025-01-01T00:00:00Z',days:[{type:'WORKOUT',name:'Push',notes:'Original warmup',exercises:[{id:'bench-plan',exerciseId:'bench',name:'Bench Press',sets:3,repMin:10,repMax:12,weight:0,rest:90},{id:'row-plan',exerciseId:'row',name:'Barbell Row',sets:3,repMin:8,repMax:12,rest:120,notes:'Use straps',groupId:'A',groupType:'SUPERSET',groupOrder:2}]},{type:'REST',name:'Rest',exercises:[]},{type:'REST',name:'Rest',exercises:[]}]}]});
const legacyVersion=clone(state.programs.at(-1).versions[0]);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push(body.action.type);state=JSON.parse(JSON.stringify(act(clone(state),body.action,today,timezone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const dialog=()=>page.getByRole('dialog'),bench=()=>dialog().locator('.prescription-card').filter({has:page.getByRole('button',{name:'Edit Bench Press prescription',exact:true})}),workout=()=>page.locator('.workout');
async function choose(name,option){await dialog().getByRole('combobox',{name,exact:true}).click();await page.getByRole('option',{name:option,exact:true}).click()}
async function saved(){await workout().getByText('Progress saved',{exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.workout fieldset:disabled'))}
async function fits(width){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px page overflow`);assert.ok(await dialog().evaluate(e=>e.scrollWidth<=e.clientWidth+1),`${width}px dialog overflow`);const bad=await dialog().locator('.planned-set-card input,.planned-set-card [role=combobox]').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect(),p=e.closest('.planned-set-card').getBoundingClientRect();return r.left<p.left-1||r.right>p.right+1}).map(e=>e.getAttribute('aria-label')));assert.deepEqual(bad,[],`${width}px inputs stay in set card`)}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('tab',{name:'Programs',exact:true}).click();await page.locator('.programcard').filter({has:page.getByRole('heading',{name:'Legacy UI',exact:true})}).getByRole('button',{name:/View|Details/}).click();await dialog().getByRole('button',{name:'Edit cycle',exact:true}).click();await dialog().getByRole('button',{name:'Edit Bench Press prescription',exact:true}).click();assert.equal(await bench().locator('.planned-set-card').count(),3);assert.equal(await dialog().getByRole('spinbutton',{name:'Bench Press set 1 minimum reps',exact:true}).inputValue(),'10');assert.equal(await dialog().getByRole('spinbutton',{name:'Bench Press set 1 maximum reps',exact:true}).inputValue(),'12');assert.equal(await dialog().getByRole('spinbutton',{name:'Bench Press set 1 rest seconds',exact:true}).inputValue(),'90');assert.equal(await dialog().getByRole('spinbutton',{name:'Bench Press set 1 target weight',exact:true}).inputValue(),'');assert.equal(await dialog().getByRole('textbox',{name:'Workout plan notes (optional)',exact:true}).inputValue(),'Original warmup');assert.equal(await dialog().locator('.planned-set-list:visible').count(),1);assert.deepEqual(state.programs.at(-1).versions[0],legacyVersion);console.log('PASS old scalar editor loads three equivalent sets, blank legacy zero and workout notes; other cards stay collapsed; no read mutation');
 await bench().getByRole('button',{name:'Duplicate previous set',exact:true}).click();await bench().getByRole('button',{name:'Add set',exact:true}).click();assert.equal(await bench().locator('.planned-set-card').count(),5);await bench().getByRole('button',{name:'Remove Bench Press set 2',exact:true}).click();assert.equal(await bench().locator('.planned-set-card').count(),4);assert.deepEqual(await bench().locator('.planned-set-card > .row > b').allTextContents(),['Set 1','Set 2','Set 3','Set 4']);
 await bench().locator('.planned-bulk > summary').click();await dialog().getByRole('spinbutton',{name:'Bench Press bulk minimum reps',exact:true}).fill('8');await dialog().getByRole('spinbutton',{name:'Bench Press bulk maximum reps',exact:true}).fill('10');await dialog().getByRole('spinbutton',{name:'Bench Press bulk rest seconds',exact:true}).fill('90');await bench().getByRole('button',{name:'Apply reps and rest to all sets',exact:true}).click();
 for(const [index,reps]of [15,12,10].entries()){const n=index+1;await choose(`Bench Press set ${n} rep type`,'Fixed reps');await dialog().getByRole('spinbutton',{name:`Bench Press set ${n} target reps`,exact:true}).fill(String(reps));if(n<3)await dialog().getByRole('spinbutton',{name:`Bench Press set ${n} rest seconds`,exact:true}).fill('60')}
 await dialog().getByRole('spinbutton',{name:'Bench Press set 1 target weight',exact:true}).fill('60');await choose('Bench Press set 2 weight unit','lb');await dialog().getByRole('spinbutton',{name:'Bench Press set 2 target weight',exact:true}).fill('154.5');await bench().locator('.planned-set-card').nth(2).locator('summary').click();await dialog().getByRole('textbox',{name:'Bench Press set 3 notes',exact:true}).fill('Dropset after this set');await dialog().getByRole('spinbutton',{name:'Bench Press set 3 target RPE',exact:true}).fill('8.5');await dialog().getByRole('textbox',{name:'Bench Press exercise notes',exact:true}).fill('Pause at the chest');await dialog().getByRole('textbox',{name:'Workout plan notes (optional)',exact:true}).fill('Warm up for 5–10 minutes.');await bench().locator('.planned-group > summary').click();await dialog().getByRole('textbox',{name:'Bench Press superset group',exact:true}).fill('A');await dialog().getByRole('spinbutton',{name:'Bench Press group order',exact:true}).fill('1');
 for(const width of [320,390,512,663,973,1440]){await fits(width);await bench().locator('.planned-set-card').first().scrollIntoViewIfNeeded();if(width===390||width===973)await page.screenshot({path:`.sites-runtime/per-set-editor-${width}.png`,animations:'disabled'})}await page.emulateMedia({colorScheme:'dark'});await fits(390);await bench().locator('.planned-set-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'.sites-runtime/per-set-editor-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});console.log('PASS bulk then per-set editing, add/duplicate/remove numbering, units/optional weight, notes/RPE/group; controls fit 320–1440px and dark mode');
 await dialog().getByRole('spinbutton',{name:'Bench Press set 1 target reps',exact:true}).fill('0');await dialog().getByRole('button',{name:'Save new version',exact:true}).click();await dialog().getByRole('alert').filter({hasText:/Minimum reps/}).waitFor();assert.equal(state.programs.at(-1).versions.length,1);await dialog().getByRole('spinbutton',{name:'Bench Press set 1 target reps',exact:true}).fill('15');
 await bench().getByRole('button',{name:'Done',exact:true}).click();assert.match(await bench().innerText(),/4 sets · 15 \/ 12 \/ 10 \/ 8–10 reps/);await dialog().getByRole('button',{name:'Save new version',exact:true}).click();await dialog().waitFor({state:'hidden'});const p=state.programs.at(-1),d=p.versions[1].days[0],sets=d.exercises[0].sets;assert.deepEqual(p.versions[0],legacyVersion);assert.deepEqual(sets.map(s=>[s.setNumber,s.repMin,s.repMax,s.restSeconds]),[[1,15,15,60],[2,12,12,60],[3,10,10,90],[4,8,10,90]]);assert.equal(displayWeight(sets[1].targetWeight,'lb'),154.5);assert.equal(sets[3].targetWeight,undefined);assert.equal(sets[2].notes,'Dropset after this set');assert.equal(sets[2].targetRpe,8.5);assert.equal(d.notes,'Warm up for 5–10 minutes.');assert.equal(d.exercises[0].groupId,'A');assert.deepEqual(plannedSets(d.exercises[1]).map(s=>[s.repMin,s.repMax,s.restSeconds]),[[8,12,120],[8,12,120],[8,12,120]]);assert.equal(d.exercises[1].notes,'Use straps');assert.equal(d.exercises[1].groupOrder,2);console.log('PASS exact round-trip prescriptions and metadata; prior version and other exercise obligations remain intact');
 await page.reload();await page.getByRole('tab',{name:'Programs',exact:true}).click();await page.locator('.programcard').filter({has:page.getByRole('heading',{name:'Legacy UI',exact:true})}).getByRole('button',{name:/View|Details/}).click();await dialog().getByText('Warm up for 5–10 minutes.',{exact:true}).waitFor();await dialog().locator('.planned-preview').first().locator('summary').click();assert.match(await dialog().locator('.planned-preview').first().innerText(),/RPE 8.5/);assert.match(await dialog().locator('.planned-preview').first().innerText(),/Dropset after this set/);await dialog().getByRole('button',{name:'Close',exact:true}).click();
 act(state,{type:'createSchedule',programId:p.id,versionId:p.versions[1].id,date:today},today,timezone);await page.reload();await page.getByRole('button',{name:'Start workout',exact:true}).click();await saved();const plans=clone(state.programs);assert.equal(state.session.exercises[0].sets.length,4);assert.equal(await workout().getByRole('spinbutton',{name:'Set 1 weight',exact:true}).inputValue(),'');assert.equal(await workout().getByRole('spinbutton',{name:'Set 1 reps',exact:true}).inputValue(),'');assert.deepEqual(await workout().locator('.set-target').allTextContents(),['Target: 15 reps · 60 kg · Rest 1:00','Target: 12 reps · 70.08002116586069 kg · Rest 1:00','Target: 10 reps · Rest 1:30 · RPE 8.5 · Dropset after this set','Target: 8–10 reps · Rest 1:30'].map(s=>s.replace('70.08002116586069','70.08')));await workout().getByText('Workout plan: Warm up for 5–10 minutes.',{exact:true}).waitFor();
 for(const width of [320,390,512,663,973,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px workout overflow`)}await page.setViewportSize({width:390,height:844});await workout().getByRole('button',{name:'Add extra set',exact:true}).click();await saved();for(const [index,duration]of [60,60,90,90].entries()){const n=index+1;await workout().getByRole('spinbutton',{name:`Set ${n} weight`,exact:true}).fill('60');await workout().getByRole('spinbutton',{name:`Set ${n} reps`,exact:true}).fill(String([15,12,10,9][index]));await workout().getByRole('checkbox',{name:`Set ${n} completed`,exact:true}).click();await saved();assert.ok(Math.abs(state.session.timerEnd-Date.now()-duration*1000)<2000,`set ${n} timer uses ${duration}s`)}assert.deepEqual(state.programs,plans);await page.screenshot({path:'.sites-runtime/per-set-workout-390.png',animations:'disabled'});await page.reload();await saved();assert.equal(state.session.exercises[0].sets.filter(s=>s.done).length,4);assert.equal(state.session.exercises[0].planned.sets[2].notes,'Dropset after this set');assert.deepEqual(errors,[]);console.log('PASS session renders individual targets and separate blank actuals, all four own timers, responsive workout and reload; actual results never alter programs; no browser errors');
}finally{await browser.close()}
