import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/cycle-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,withPresets,currentProgram,nextProgramWorkout,projection,addDays}=await import('../.sites-runtime/tests/cycle-domain.mjs');
const today='2026-10-07',zone='Asia/Bangkok';const action=(s,a,date=today)=>act(s,a,date,zone);
function fixture(){const s=initialState();action(s,{type:'duplicateProgram',id:s.programs[0].id});const p=s.programs.at(-1);action(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id});return s}
function finish(s,date=today){action(s,{type:'startWorkout',date},date);action(s,{type:'finishWorkout',confirmIncomplete:true},date)}
function version(s){const p=s.programs.at(-1),days=clone(p.versions[0].days);days[0].name='New Push';action(s,{type:'saveProgram',id:p.id,name:p.name,days});return {programId:p.id,versionId:p.versions.at(-1).id}}

test('dates and rest do not advance the next workout; future projection is empty',()=>{const s=fixture(),before=clone(s);for(const date of [today,addDays(today,1),addDays(today,70)])assert.equal(nextProgramWorkout(s,date).day.name,'Push');assert.equal(projection(s,addDays(today,1),today),null);assert.equal(projection(s,addDays(today,-1),today),null);assert.deepEqual(s,before)});
test('Finish advances once, including partial/all-skipped sessions, and wraps the workout-only cycle',()=>{const s=fixture();assert.equal(currentProgram(s,today).workouts.length,3);finish(s);assert.equal(nextProgramWorkout(s,today).day.name,'Pull');assert.throws(()=>action(s,{type:'finishWorkout',confirmIncomplete:true}),/No active workout/);finish(s,addDays(today,6));assert.equal(nextProgramWorkout(s,addDays(today,40)).day.name,'Legs');action(s,{type:'startWorkout',date:today});for(const exercise of s.session.exercises)action(s,{type:'skipExercise',id:exercise.id,skipped:true});action(s,{type:'finishWorkout'});assert.equal(nextProgramWorkout(s,today).day.name,'Push');assert.equal(currentProgram(s,today).cursor.cycleNumber,2);assert.equal(s.logs.length,3)});
test('discard and unscheduled workouts do not advance the active cycle',()=>{const s=fixture(),cursor=clone(currentProgram(s,today).cursor);action(s,{type:'startWorkout',date:today});action(s,{type:'addSet',exerciseId:s.session.exercises[0].id});action(s,{type:'discardWorkout',confirmed:true});assert.deepEqual(currentProgram(s,today).cursor,cursor);assert.equal(s.logs.length,0);action(s,{type:'startWorkout',date:today,unscheduled:true});action(s,{type:'addExercise',exerciseId:'bench'});Object.assign(s.session.exercises[0].sets[0],{done:true,reps:8,weight:20});action(s,{type:'finishWorkout'});assert.deepEqual(currentProgram(s,today).cursor,cursor)});
test('Apply now resets to Workout 1 of new version and leaves previous History byte-for-byte unchanged',()=>{const s=fixture();finish(s);const history=clone(s.logs),next=version(s);action(s,{type:'applyVersion',...next,mode:'NOW'});assert.equal(nextProgramWorkout(s,today).day.name,'New Push');assert.equal(currentProgram(s,today).cursor.cycleNumber,1);assert.deepEqual(s.logs,history);assert.equal(s.schedules[0].applications.length,2)});
test('queued version activates only after final finished workout, independent of dates',()=>{const s=fixture(),next=version(s);action(s,{type:'applyVersion',...next,mode:'AFTER_CYCLE'});const cursor=clone(currentProgram(s,today).cursor);assert.equal(nextProgramWorkout(s,addDays(today,100)).versionNumber,1);assert.deepEqual(currentProgram(s,today).cursor,cursor);finish(s);assert.equal(nextProgramWorkout(s,today).day.name,'Pull');finish(s);assert.equal(nextProgramWorkout(s,today).day.name,'Legs');const history=clone(s.logs);finish(s);assert.equal(nextProgramWorkout(s,today).day.name,'New Push');assert.equal(nextProgramWorkout(s,today).versionNumber,2);assert.equal(currentProgram(s,today).cursor.index,0);assert.equal(currentProgram(s,today).cursor.cycleNumber,1);assert.equal(currentProgram(s,today).cursor.queued,null);assert.deepEqual(s.logs.slice(0,2),history)});
test('queued changes can be cancelled and replaced; active session blocks Apply now but allows queue',()=>{const s=fixture(),next=version(s);action(s,{type:'startWorkout',date:today});const session=clone(s.session);assert.throws(()=>action(s,{type:'applyVersion',...next,mode:'NOW'}),/Finish or discard/);assert.deepEqual(s.session,session);action(s,{type:'applyVersion',...next,mode:'AFTER_CYCLE'});assert.throws(()=>action(s,{type:'applyVersion',...next,mode:'AFTER_CYCLE'}),/Cancel the queued/);action(s,{type:'cancelFuture'});assert.equal(currentProgram(s,today).cursor.queued,null);assert.deepEqual(s.session,session)});
test('legacy schedule migration follows last recorded workout, removes Rest from progression, preserves log snapshots',()=>{const s=fixture(),sch=s.schedules[0],app=sch.applications[0],p=s.programs.at(-1);p.versions[0].days.splice(2,0,{type:'REST',name:'Rest',exercises:[]});finish(s);const log=s.logs[0];log.occurrence.id='legacy-date-id';log.occurrence.cycleNumber=4;log.date='2026-10-01';sch.start='2026-09-01';delete sch.cycleState;const history=clone(s.logs),programs=clone(s.programs);withPresets(s);assert.equal(currentProgram(s,today).cursor.index,1);assert.equal(currentProgram(s,today).cursor.cycleNumber,4);assert.equal(nextProgramWorkout(s,today).day.name,'Pull');assert.deepEqual(s.logs,history);assert.deepEqual(s.programs,programs);const migrated=clone(s);withPresets(s);assert.deepEqual(s,migrated);assert.equal(sch.cycleState.appId,app.id)});
test('migration preserves a legacy active session and finishing it advances from its actual workout',()=>{const s=fixture(),p=s.programs.at(-1);p.versions[0].days.splice(2,0,{type:'REST',name:'Rest',exercises:[]});finish(s);finish(s);action(s,{type:'startWorkout',date:today});const session=clone(s.session);delete s.schedules[0].cycleState;withPresets(s);assert.deepEqual(s.session,session);assert.equal(currentProgram(s,today).cursor.index,2);action(s,{type:'finishWorkout',confirmIncomplete:true});assert.equal(nextProgramWorkout(s,today).day.name,'Push');assert.equal(currentProgram(s,today).cursor.cycleNumber,2)});
test('historical correction changes results without advancing or rewinding the cycle',()=>{const s=fixture();finish(s);const cursor=clone(currentProgram(s,today).cursor),log=s.logs[0],exercises=clone(log.exercises);Object.assign(exercises[0].sets[0],{done:true,reps:8,weight:20});action(s,{type:'correctLog',id:log.id,exercises,notes:'Corrected',confirmed:true});assert.deepEqual(currentProgram(s,today).cursor,cursor)});
test('new saved cycles contain only workouts, including existing Rest-based programs',()=>{const s=fixture(),p=s.programs.at(-1),days=clone(p.versions[0].days);days.splice(1,0,{type:'REST',name:'Rest',exercises:[]});action(s,{type:'saveProgram',id:p.id,name:p.name,days});assert.equal(p.versions.at(-1).days.length,3);assert.ok(p.versions.at(-1).days.every(d=>d.type==='WORKOUT'));assert.throws(()=>action(s,{type:'saveProgram',name:'Rest only',days:[{type:'REST',name:'Rest',exercises:[]}]}),/1 to 12/)});
test('fixed calendar activation/moves and past/future starts cannot bypass the cycle model',()=>{const s=fixture(),next=version(s);assert.throws(()=>action(s,{type:'applyVersion',...next,date:addDays(today,1)}),/Apply now/);for(const type of ['override','replaceOccurrence'])assert.throws(()=>action(s,{type}),/cycle/);for(const date of [addDays(today,-1),addDays(today,1)])assert.throws(()=>action(s,{type:'startWorkout',date}),/Today/);assert.equal(currentProgram(s,today).cursor.index,0)});
