import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {initialState,act,clone,localDate,addDays,currentProgram}=await import('../.sites-runtime/tests/cycle-domain.mjs');const today=localDate(),zone='Asia/Bangkok';let state=initialState(),revision=0;const errors=[];
function action(a){state=act(state,a,today,zone);revision++}action({type:'duplicateProgram',id:state.programs[0].id});const pid=state.programs.at(-1).id;action({type:'createSchedule',programId:pid,versionId:state.programs.at(-1).versions[0].id});action({type:'startWorkout',date:today});action({type:'finishWorkout',confirmIncomplete:true});const originalHistory=clone(state.logs);function newVersion(name){const p=state.programs.find(p=>p.id===pid),days=clone(p.versions.at(-1).days);days[0].name=name;action({type:'saveProgram',id:pid,name:p.name,days})}newVersion('New Push');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST')action(route.request().postDataJSON().action);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message,code:e.code})})}});
const dialog=()=>page.getByRole('dialog'),manage=async()=>{await page.getByRole('button',{name:'Manage program',exact:true}).click();await dialog().getByRole('heading',{name:'Manage program',exact:true}).waitFor()},close=async()=>{await dialog().getByRole('button',{name:'Close',exact:true}).click();await dialog().waitFor({state:'hidden'})};async function finish(){await page.getByRole('button',{name:/^Start workout ·/}).click();await page.locator('.workout').waitFor();await page.locator('.workout').getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('heading',{name:'Workout Summary',exact:true}).waitFor();await page.getByRole('button',{name:'Back to schedule',exact:true}).click();await page.locator('.daydetail').waitFor()}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.locator('.daydetail').getByRole('heading',{name:'Pull',exact:true}).waitFor();assert.match(await page.locator('.daydetail').innerText(),/Workout 2 of 3/);assert.equal(await page.locator('.calendar .dayname').filter({hasText:/Push|Pull|Legs|Rest/}).count(),0);const future=await page.locator('.calendar .week button:disabled').all();assert.ok(future.length>0);for(const button of future)assert.equal(await button.getAttribute('aria-pressed'),'false');await page.setViewportSize({width:982,height:844});await page.locator('.calendar input[type=date]').fill(addDays(today,1));assert.equal(await page.locator('.daydetail').getByRole('heading',{name:'Pull',exact:true}).count(),1);await page.getByRole('button',{name:'Previous week',exact:true}).click();await page.getByRole('heading',{name:'No workout recorded',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:/^Start workout ·/}).count(),0);await page.getByRole('button',{name:'Back to Today',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await manage();await dialog().getByText('Workout 2 of 3 · Pull',{exact:true}).waitFor();assert.equal(await dialog().locator('input[type=date]').count(),0);assert.equal(await dialog().getByRole('button',{name:'End schedule today',exact:true}).count(),0);assert.equal(await dialog().getByRole('heading',{name:'Schedule preview',exact:true}).count(),0);
 for(const width of [320,390,668,982]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await dialog().evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.ok((await dialog().boundingBox()).width<=480);if(width===390)await page.screenshot({path:'.sites-runtime/manage-program-390.png',animations:'disabled'})}await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:'.sites-runtime/manage-program-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});await page.setViewportSize({width:390,height:844});await dialog().getByRole('button',{name:'Apply after current cycle',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.equal(currentProgram(state,today).version.number,1);assert.ok(currentProgram(state,today).cursor.queued);await manage();await dialog().getByText('Applies after current cycle',{exact:true}).waitFor();await dialog().getByRole('button',{name:'Cancel version change',exact:true}).click();await dialog().getByRole('button',{name:'Apply after current cycle',exact:true}).waitFor();assert.equal(currentProgram(state,today).cursor.queued,null);await dialog().getByRole('button',{name:'Apply after current cycle',exact:true}).click();await dialog().waitFor({state:'hidden'});
 await finish();assert.equal(currentProgram(state,today).version.number,1);assert.equal(currentProgram(state,today).cursor.index,2);await finish();assert.equal(currentProgram(state,today).version.number,2);assert.equal(currentProgram(state,today).cursor.index,0);assert.deepEqual(state.logs.slice(0,1),originalHistory);await page.locator('.daydetail').getByRole('heading',{name:'New Push',exact:true}).waitFor();
 newVersion('Latest Push');await page.reload();await manage();await dialog().getByRole('button',{name:'Apply now',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.equal(currentProgram(state,today).version.number,3);assert.equal(currentProgram(state,today).cursor.index,0);
 for(const label of ['Schedule','Programs','History','Settings']){await page.getByRole('tab',{name:label,exact:true}).click();const active=page.locator('.mainnav [data-state=active]');await page.waitForFunction(()=>getComputedStyle(document.querySelector('.mainnav [data-state=active]')).color==='rgb(255, 255, 255)');assert.equal(await active.innerText(),label);assert.equal(await active.evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');assert.match(await active.evaluate(e=>getComputedStyle(e).backgroundImage),/59, 130, 246/);assert.equal(await active.locator('svg').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');assert.equal(await page.locator('.mainnav').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(255, 255, 255, 0.72)');await page.screenshot({path:`.sites-runtime/nav-${label.toLowerCase()}.png`,animations:'disabled'})}
 await page.getByRole('tab',{name:'Programs',exact:true}).click();await page.getByRole('button',{name:'Create program',exact:true}).click();await dialog().getByRole('heading',{name:'Create program',exact:true}).waitFor();assert.equal(await dialog().getByRole('combobox',{name:'Day type',exact:true}).count(),0);assert.equal(await dialog().getByText('Rest day',{exact:true}).count(),0);await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await dialog().waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);console.log('PASS completion-driven Schedule, history-only calendar and disabled future dates; Manage program mobile/dark layout; queue/cancel/boundary activation; Apply now reset; History preserved; shared blue/glass nav on all tabs; workout-only editor.');
}catch(error){await page.screenshot({path:'.sites-runtime/program-cycle-failure.png'});console.error(await page.locator('body').innerText());throw error}finally{await browser.close()}
