import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/glass-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,localDate,addDays}=await import('../.sites-runtime/tests/glass-domain.mjs');
const today=localDate(),yesterday=addDays(today,-1),zone='Asia/Bangkok';
function fixture(start=yesterday){const s=initialState();act(s,{type:'duplicateProgram',id:s.programs[0].id},start,zone);const p=s.programs.at(-1);act(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id,date:start},start,zone);return s}
let state=fixture(),revision=0;const errors=[],actions=[];
act(state,{type:'startWorkout',date:yesterday},yesterday,zone);const ex=clone(state.session.exercises);Object.assign(ex[0].sets[0],{weight:70,reps:10,done:true});act(state,{type:'saveSession',id:state.session.id,name:state.session.name,notes:'',exercises:ex},yesterday,zone);act(state,{type:'finishWorkout',confirmIncomplete:true},yesterday,zone);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:982,height:871},colorScheme:'light'});
page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push(body.action);state=JSON.parse(JSON.stringify(act(clone(state),body.action,today,zone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const dialog=()=>page.getByRole('alertdialog'),stop=()=>page.locator('.stop-program'),css=(selector,property)=>page.locator(selector).first().evaluate((e,p)=>getComputedStyle(e).getPropertyValue(p),property);
async function fits(){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(await dialog().count())assert.equal(await dialog().evaluate(e=>e.scrollWidth>e.clientWidth),false)}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'Pull',exact:true}).waitFor();assert.equal(await page.locator('.cycle [aria-current=step]').innerText(),'2 Pull');assert.equal(await css('.week .selected','color'),'rgb(255, 255, 255)');assert.equal(await css('.week .selected .weekday','color'),'rgb(255, 255, 255)');assert.equal(await css('.week .selected .daymark','color'),'rgb(255, 255, 255)');assert.equal(await css('.mainnav [data-state=active]','color'),'rgb(255, 255, 255)');assert.match(await css('.calendar','backdrop-filter'),/blur\(20px\).*saturate\(1.8\)/);assert.equal(await css('.status.planned','color'),'rgb(29, 78, 216)');assert.equal(await page.locator('.week .daymark.complete').count(),1);
 for(const width of [320,390,668,982,1440]){await page.setViewportSize({width,height:871});await fits();if(width===390||width===982)await page.screenshot({path:`.sites-runtime/schedule-glass-${width}.png`,animations:'disabled'})}
 await page.getByRole('button',{name:'Next week',exact:true}).click();await page.getByRole('button',{name:'Previous week',exact:true}).click();await page.getByRole('button',{name:'Today',exact:true}).click();await page.getByRole('textbox',{name:'Jump to date',exact:true}).fill(addDays(today,2));await page.getByRole('button',{name:'Today',exact:true}).click();await page.locator('.planned-preview summary').first().click();await page.locator('.planned-preview[open]').first().waitFor();await page.getByRole('button',{name:'Manage schedule',exact:true}).click();await page.getByRole('dialog').getByRole('heading',{name:'Manage schedule',exact:true}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();assert.deepEqual(actions,[]);
 await stop().click();await dialog().waitFor();await dialog().evaluate(e=>Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))));assert.equal(await dialog().getByRole('button',{name:'Cancel',exact:true}).evaluate(e=>e===document.activeElement),true);assert.match(await dialog().innerText(),/Today will be the final scheduled day/);assert.match(await css('.stop-dialog-confirm','background-image'),/220, 38, 38/);for(const width of [320,390,982]){await page.setViewportSize({width,height:871});await fits();const cancel=await dialog().getByRole('button',{name:'Cancel',exact:true}).boundingBox(),confirm=await dialog().getByRole('button',{name:'Stop program',exact:true}).boundingBox();assert.ok(cancel.x<confirm.x);assert.equal(await css('.stop-dialog-actions','flex-direction'),'row');assert.ok(await dialog().locator('.stop-dialog-actions').evaluate(e=>Array.from(e.children).every(b=>parseFloat(getComputedStyle(b).height)>=44)));if(width===390||width===982)await page.screenshot({path:`.sites-runtime/stop-glass-${width}.png`,animations:'disabled'})}
 await page.keyboard.press('Escape');await dialog().waitFor({state:'hidden'});assert.deepEqual(actions,[]);await stop().click();await dialog().waitFor();await page.mouse.click(5,5);await dialog().waitFor({state:'hidden'});assert.deepEqual(actions,[]);await stop().click();await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await dialog().waitFor({state:'hidden'});
 await page.emulateMedia({colorScheme:'dark'});assert.equal(await css('.week .selected .weekday','color'),'rgb(255, 255, 255)');await page.screenshot({path:'.sites-runtime/schedule-glass-dark.png',animations:'disabled'});await stop().click();await dialog().waitFor();await page.screenshot({path:'.sites-runtime/stop-glass-dark.png',animations:'disabled'});await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await css('.stop-program-dialog','animation-name'),'none');await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await dialog().waitFor({state:'hidden'});await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});
 const plans=clone(state.programs),logs=clone(state.logs);await stop().click();await dialog().getByRole('button',{name:'Stop program',exact:true}).click();await page.getByRole('heading',{name:'No active schedule',exact:true}).waitFor();assert.equal(state.schedules[0].status,'ENDED');assert.deepEqual(state.programs,plans);assert.deepEqual(state.logs,logs);await fits();assert.match(await css('.calendar-empty .selected','background-image'),/30, 64, 175/);
 state=fixture(today);act(state,{type:'startWorkout',date:today},today,zone);revision++;await page.reload();await stop().click();await dialog().getByText('Your active workout and rest timer will stop now. Recorded results will be saved to History. Future workouts will stop; your saved programs will be kept.',{exact:true}).waitFor();await dialog().getByRole('button',{name:'Stop program',exact:true}).click();await page.getByRole('heading',{name:'No active schedule',exact:true}).waitFor();assert.equal(state.session,null);assert.equal(state.logs.length,1);
 state=fixture(addDays(today,2));revision++;await page.reload();await stop().click();await dialog().getByText('This will cancel the upcoming training schedule. Your saved programs and workout history will be kept.',{exact:true}).waitFor();await dialog().getByRole('button',{name:'Stop program',exact:true}).click();await page.getByRole('heading',{name:'No active schedule',exact:true}).waitFor();assert.equal(state.schedules[0].status,'CANCELLED');assert.deepEqual(errors,[]);
 console.log('PASS glass/selected states; 320–1440px, light/dark, reduced motion, calendar/date/Manage/set targets; cancel/Esc/backdrop do not mutate data, safe initial focus, confirmed stop preserves history/programs, stops active workout and cancels future schedule.');
}finally{await browser.close()}


