import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const require=createRequire(import.meta.url),pw=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/background-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone}=await import('../.sites-runtime/tests/background-domain.mjs'),today='2026-10-07',zone='Asia/Bangkok';
const state=initialState();act(state,{type:'duplicateProgram',id:state.programs[0].id},today,zone);const p=state.programs.at(-1);act(state,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id},today,zone);act(state,{type:'startWorkout',date:today},today,zone);Object.assign(state.session.exercises[0].sets[0],{done:true,weight:20,reps:8});act(state,{type:'finishWorkout',confirmIncomplete:true},today,zone);const first=clone(state.logs[0]);state.logs=Array.from({length:12},(_,i)=>({...clone(first),id:`bg-${i}`,finishedAt:new Date(Date.parse('2026-10-07T05:00:00Z')-i*60000).toISOString()}));
const browserName=process.env.TEST_BROWSER||'chromium',browser=await pw[browserName].launch({headless:true,...(browserName==='chromium'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});
const page=await browser.newPage({viewport:{width:390,height:844},timezoneId:zone,isMobile:true,hasTouch:true,colorScheme:'light',reducedMotion:'reduce'});const errors=[],posts=[];
page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/training',async r=>{if(r.request().method()==='POST')posts.push(r.request().postDataJSON());await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision:0})})});
const geometry=()=>page.locator('.shell').evaluate(e=>({height:document.documentElement.scrollHeight,content:e.textContent,boxes:[...e.querySelectorAll('header,.pagehead,.calendar,.schedulegrid,.panel,.recentlog')].map(n=>{const b=n.getBoundingClientRect(),s=getComputedStyle(n);return {x:b.x,y:b.y+scrollY,width:b.width,height:b.height,padding:s.padding,gap:s.gap,background:s.background,color:s.color,border:s.border,borderRadius:s.borderRadius,font:s.font}})}));
try{
 await page.clock.install({time:new Date('2026-10-07T05:00:00Z')});await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.locator('.calendar').waitFor();await page.evaluate(()=>document.fonts.ready);await page.clock.runFor(2600);
 for(const theme of ['light','dark']){await page.emulateMedia({colorScheme:theme});for(const width of [375,390,430]){
  await page.setViewportSize({width,height:844});await page.evaluate(()=>scrollTo(0,0));await page.clock.runFor(2600);
  const fixed=await geometry(),root=await page.locator('html').evaluate(e=>{const s=getComputedStyle(e);return {image:s.backgroundImage,attachment:s.backgroundAttachment,filter:s.filter,transform:s.transform,clip:s.clipPath}});
  assert.ok(root.attachment.split(',').every(value=>value.trim()==='scroll'));assert.match(root.image,/radial-gradient/);assert.equal(root.filter,'none');assert.equal(root.transform,'none');assert.equal(root.clip,'none');assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).backgroundImage),'none');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const legacy=await page.addStyleTag({content:`html:has(.shell){background:transparent!important}body:has(.shell){background-image:${root.image}!important;background-attachment:fixed!important}`});
  assert.deepEqual(await geometry(),fixed,'Background refactor must not change any content/card geometry or styles');await page.screenshot({path:`.sites-runtime/background-${browserName}-${theme}-${width}-legacy-viewport.png`,animations:'disabled'});await legacy.evaluate(e=>e.remove());await page.clock.runFor(50);
  await page.screenshot({path:`.sites-runtime/background-${browserName}-${theme}-${width}-viewport.png`,animations:'disabled'});
  await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.clock.runFor(2600);const scrolled=await geometry();assert.deepEqual(scrolled,fixed);await page.screenshot({path:`.sites-runtime/background-${browserName}-${theme}-${width}-scrolled.png`,animations:'disabled'});
  await page.setViewportSize({width,height:724});await page.clock.runFor(2600);assert.deepEqual(await geometry(),fixed,'Toolbar-sized viewport changes must not shift document content');await page.setViewportSize({width,height:844});await page.clock.runFor(2600);
  const captureHeight=await page.evaluate(()=>document.documentElement.scrollHeight);await page.screenshot({path:`.sites-runtime/background-${browserName}-${theme}-${width}-full.png`,fullPage:true,animations:'disabled'});assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight),captureHeight);
 }
 await page.emulateMedia({media:'print'});assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).backgroundImage),'none');assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).backgroundColor),theme==='light'?'rgb(239, 244, 250)':'rgb(11, 18, 32)');assert.equal(await page.locator('.recentlog').count(),12);await page.screenshot({path:`.sites-runtime/background-${browserName}-${theme}-print.png`,fullPage:true,animations:'disabled'});if(browserName==='chromium')await page.pdf({path:`.sites-runtime/schedule-${theme}.pdf`,printBackground:true,preferCSSPageSize:true});await page.emulateMedia({media:'screen'});
 }
 assert.equal(posts.length,0);assert.deepEqual(errors,[]);console.log(`PASS ${browserName}: unchanged Schedule content/card geometry and styles; root-only non-fixed gradients; light/dark 375/390/430px viewport/scroll/dynamic-height/full-page captures; print fallback${browserName==='chromium'?' and PDF generation':''}; no training writes. Native iOS Full Page UI is not automated by this test.`);
}finally{await browser.close()}
