import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {initialState,act,clone,localDate}=await import('../.sites-runtime/tests/user-ppl-domain.mjs');
const today=localDate(),zone='Asia/Bangkok';let state=initialState(),revision=0;const errors=[];
const original=clone(state.programs.find(p=>p.id==='preset-user-ppl'));
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const body=route.request().postDataJSON();state=JSON.parse(JSON.stringify(act(clone(state),body.action,today,zone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const dialog=()=>page.getByRole('dialog'),workout=()=>page.locator('.workout');
async function saved(){await workout().getByText('Progress saved',{exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.workout fieldset:disabled'))}
async function fits(){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await dialog().evaluate(e=>e.scrollWidth<=e.clientWidth+1))}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('tab',{name:'Programs',exact:true}).click();const card=page.locator('.programcard').filter({has:page.getByRole('heading',{name:'User PPL',exact:true})});await card.getByRole('button',{name:'Choose preset',exact:true}).click();await dialog().getByRole('heading',{name:'Choose your repeating cycle',exact:true}).waitFor();assert.equal(await dialog().getByRole('radio').count(),3);assert.equal(await dialog().getByRole('radio',{checked:true}).count(),0);assert.equal(await dialog().getByRole('button',{name:'Save cycle & continue',exact:true}).isDisabled(),true);assert.equal(state.schedules.length,0);assert.equal(state.programs.at(-1).preset,undefined);assert.deepEqual(state.programs.find(p=>p.id==='preset-user-ppl'),original);await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await page.locator('.programcard').filter({has:page.getByRole('button',{name:'Set up cycle',exact:true})}).getByRole('button',{name:'Set up cycle',exact:true}).click();for(const width of [320,390,973]){await page.setViewportSize({width,height:900});await fits();if(width===390)await page.screenshot({path:'.sites-runtime/user-ppl-cycle-390.png',animations:'disabled'})}await dialog().locator('.preset-cycle-option').filter({hasText:'3-day cycle'}).getByRole('radio').click();await dialog().getByRole('button',{name:'Save cycle & continue',exact:true}).click();await dialog().getByRole('heading',{name:'Choose start date',exact:true}).waitFor();assert.equal(state.schedules.length,0);assert.equal(state.programs.at(-1).needsCycleSetup,undefined);assert.equal(state.programs.at(-1).versions[0].templateOnly,true);assert.equal(state.programs.at(-1).versions.at(-1).templateOnly,undefined);await dialog().getByRole('button',{name:'Close',exact:true}).click();const copy=state.programs.at(-1);await page.locator('.programcard').filter({has:page.getByRole('heading',{name:'User PPL',exact:true})}).filter({has:page.getByRole('button',{name:'View program',exact:true})}).getByRole('button',{name:'View program',exact:true}).click();
 await dialog().getByRole('tab',{name:'Day 2',exact:true}).click();await dialog().getByText('Estimated duration: ~120 minutes.',{exact:true}).waitFor();await dialog().locator('.planned-preview').first().locator('summary').click();assert.match(await dialog().locator('.planned-preview').first().innerText(),/Rest 2:00–3:00 · RPE 8.5/);assert.equal(await dialog().locator('.planlist > div').count(),9);await dialog().getByRole('tab',{name:'Day 3',exact:true}).click();assert.match(await dialog().locator('.planned-workout-notes').innerText(),/Warmup: 5–10 minutes before Squat/);await dialog().getByRole('button',{name:'Edit cycle',exact:true}).click();await dialog().getByRole('tab',{name:/^Day 2:/}).click();await dialog().getByRole('button',{name:'Edit Barbell Row prescription',exact:true}).click();assert.equal(await dialog().getByRole('spinbutton',{name:'Barbell Row set 1 rest seconds',exact:true}).inputValue(),'120');assert.equal(await dialog().getByRole('spinbutton',{name:'Barbell Row set 1 maximum rest seconds',exact:true}).inputValue(),'180');assert.equal(await dialog().getByRole('spinbutton',{name:'Barbell Row set 1 target RPE',exact:true}).inputValue(),'8.5');assert.equal(await dialog().getByRole('spinbutton',{name:'Barbell Row set 1 target weight',exact:true}).inputValue(),'');
 for(const width of [320,390,663,973,1440]){await page.setViewportSize({width,height:900});await fits();await dialog().locator('.planned-set-card').first().scrollIntoViewIfNeeded();if(width===390||width===973)await page.screenshot({path:`.sites-runtime/user-ppl-rest-range-${width}.png`,animations:'disabled'})}await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:'dark'});await fits();await page.screenshot({path:'.sites-runtime/user-ppl-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});
 await dialog().getByRole('spinbutton',{name:'Barbell Row set 1 maximum rest seconds',exact:true}).fill('100');await dialog().getByRole('button',{name:'Save new version',exact:true}).click();await dialog().getByRole('alert').filter({hasText:/Maximum rest/}).waitFor();assert.equal(state.programs.at(-1).versions.length,2);await dialog().getByRole('spinbutton',{name:'Barbell Row set 1 maximum rest seconds',exact:true}).fill('150');await dialog().getByRole('button',{name:'Save new version',exact:true}).click();await dialog().waitFor({state:'hidden'});const savedCopy=state.programs.at(-1);assert.equal(savedCopy.versions[1].days[1].exercises[0].sets[0].restSecondsMax,180);assert.equal(savedCopy.versions.at(-1).days[1].exercises[0].sets[0].restSecondsMax,150);assert.deepEqual(state.programs.find(p=>p.id==='preset-user-ppl'),original);console.log('PASS explicit cycle selection/cancel/resume and chooser saves editable copy without starting a schedule; exact rich previews, range editing/validation, blank weights, RPE, warmup, responsive 320–1440px and dark mode');
 const allPlans=clone(state.programs);act(state,{type:'createSchedule',programId:copy.id,versionId:savedCopy.versions.at(-1).id,date:today},today,zone);act(state,{type:'replaceOccurrence',date:today,programId:copy.id,versionId:savedCopy.versions.at(-1).id,dayIndex:1},today,zone);act(state,{type:'startWorkout',date:today},today,zone);await page.reload();await saved();assert.equal(state.session.exercises.length,9);assert.equal(state.session.exercises.reduce((n,e)=>n+e.sets.length,0),29);assert.match(await workout().locator('.set-target').first().innerText(),/Rest 2:00–2:30 · RPE 8.5/);await workout().getByRole('spinbutton',{name:'Set 1 weight',exact:true}).fill('60');await workout().getByRole('spinbutton',{name:'Set 1 reps',exact:true}).fill('7');await workout().getByRole('checkbox',{name:'Set 1 completed',exact:true}).click();await saved();assert.ok(Math.abs(state.session.timerEnd-Date.now()-120000)<2000);await workout().getByText('Target rest: 2:00–2:30. Timer starts at 2:00; add 30s as needed.',{exact:true}).waitFor();const end=state.session.timerEnd;await workout().getByRole('button',{name:'+30s',exact:true}).click();await saved();assert.equal(state.session.timerEnd,end+30000);await page.reload();await saved();assert.equal(state.session.exercises[0].planned.sets[0].restSecondsMax,150);assert.deepEqual(state.programs,allPlans);assert.deepEqual(errors,[]);console.log('PASS Pull generates 29 actual rows; range target survives session/reload, timer starts at 120s, +30s works, programs stay unchanged and no runtime errors');
}finally{await browser.close()}
