import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';export * from './lib/workout-acknowledgement';export * from './lib/workout-duration';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/acknowledgement-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,localDate,workoutAcknowledgement,workoutDuration,currentProgram}=await import('../.sites-runtime/tests/acknowledgement-domain.mjs'),today=localDate(),zone='Asia/Bangkok';
function fixture({index=1,partial=false,queued=false}={}){
 const s=initialState();act(s,{type:'duplicateProgram',id:s.programs[0].id},today,zone);const p=s.programs.at(-1);
 act(s,{type:'createSchedule',programId:p.id,versionId:p.versions[0].id},today,zone);s.schedules[0].cycleState.index=index;s.schedules[0].cycleState.cycleNumber=4;
 if(queued){const days=clone(p.versions[0].days);days[0].name='New Push';act(s,{type:'saveProgram',id:p.id,name:p.name,days},today,zone);act(s,{type:'applyVersion',mode:'AFTER_CYCLE',programId:p.id,versionId:p.versions[1].id},today,zone)}
 act(s,{type:'startWorkout',date:today},today,zone);s.session.startedAt=new Date(Date.now()-763000).toISOString();
 for(const e of s.session.exercises)for(const set of e.sets)Object.assign(set,{done:true,reps:10,weight:20});
 if(partial){const sets=s.session.exercises[0].sets;sets[0].done=false;sets[0].skipped=true;sets[1].done=false;sets[1].reps=9;sets[1].weight=22}
 s.session.exercises[0].sets.push({id:'extra-qa',planned:false,done:true,reps:12,weight:25});return s;
}
let state=fixture(),revision=0;const errors=[],actions=[];
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const {action}=route.request().postDataJSON();actions.push(action);state=JSON.parse(JSON.stringify(act(clone(state),action,today,zone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const popup=()=>page.getByRole('dialog'),banner=()=>page.getByRole('region',{name:'Workout acknowledgement',exact:true});
async function finish(){const original=clone(state.session);await page.locator('.workout').getByRole('button',{name:'Finish workout',exact:true}).click();const confirmation=page.getByRole('alertdialog');if(await confirmation.count())await confirmation.getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('heading',{name:'Workout Summary',exact:true}).waitFor();assert.equal(await popup().count(),0);assert.equal(await banner().count(),0);assert.equal(state.session,null);assert.equal(state.logs.length,1);assert.equal(state.logs[0].startedAt,original.startedAt);assert.deepEqual(state.logs[0].exercises,original.exercises);assert.equal(await page.getByLabel('Total workout duration',{exact:true}).innerText(),`Duration: ${workoutDuration(original.startedAt,Date.parse(state.logs[0].finishedAt))}`);await page.getByRole('region',{name:'Exercise breakdown',exact:true}).waitFor();await page.getByText('+1 extra set completed',{exact:true}).waitFor()}
async function reset(options){state=fixture(options);revision++;await page.reload({waitUntil:'domcontentloaded'});await page.locator('.workout').waitFor()}
async function done(){await page.getByRole('button',{name:'Done',exact:true}).click()}
async function dismiss(){await popup().getByRole('button',{name:'Dismiss workout acknowledgement',exact:true}).click();await popup().waitFor({state:'hidden'})}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await page.locator('.workout').waitFor();await finish();assert.equal(currentProgram(state,today).cursor.index,2);await done();await popup().getByRole('heading',{name:'KUDOS!',exact:true}).waitFor();await popup().getByText('Great work.',{exact:true}).waitFor();await popup().getByText('Next: Workout 3 of 3 · Legs',{exact:true}).waitFor();assert.equal(await popup().getByText(/momentum|Restart program|Program completed/).count(),0);
 assert.equal(await popup().getByRole('heading',{name:'KUDOS!',exact:true}).evaluate(e=>getComputedStyle(e).fontWeight),'800');assert.ok(Math.abs(await popup().getByRole('heading',{name:'KUDOS!',exact:true}).evaluate(e=>parseFloat(getComputedStyle(e).letterSpacing)/parseFloat(getComputedStyle(e).fontSize))-.05)<1e-6);
 for(const width of [320,390,982]){await page.setViewportSize({width,height:844});await page.screenshot({path:`.sites-runtime/kudos-daylight-${width}.png`,animations:'disabled'});const box=await popup().boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width,JSON.stringify({width,box}));assert.ok(box.height<500);assert.equal(await popup().evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.equal(await page.locator('.workout-acknowledgement-overlay').evaluate(e=>getComputedStyle(e).backdropFilter),'blur(12px)')}
 await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:'.sites-runtime/kudos-daylight-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});await page.keyboard.press('Escape');await popup().waitFor({state:'hidden'});const cursor=clone(state.schedules[0].cycleState);await page.getByRole('tab',{name:'History',exact:true}).click();await page.getByRole('tab',{name:'Schedule',exact:true}).click();assert.equal(await popup().count(),0);assert.equal(await banner().count(),0);await page.reload();await page.locator('.calendar').waitFor();assert.equal(await popup().count(),0);assert.equal(await banner().count(),0);assert.deepEqual(state.schedules[0].cycleState,cursor);
 await reset({index:2});await finish();await page.getByRole('region',{name:'Cycle completed',exact:true}).getByText('You finished all 3 workouts.',{exact:true}).waitFor();assert.equal(currentProgram(state,today).cursor.index,0);assert.equal(currentProgram(state,today).cursor.cycleNumber,5);assert.equal(currentProgram(state,today).schedule.status,'ACTIVE');await done();await popup().getByRole('heading',{name:'CYCLE COMPLETE',exact:true}).waitFor();await popup().getByText('You finished all 3 workouts.',{exact:true}).waitFor();await popup().getByText('Next: Workout 1 of 3 · Push',{exact:true}).waitFor();await dismiss();await page.getByRole('tab',{name:'Programs',exact:true}).click();await page.locator('.program-active').getByText('Active',{exact:true}).waitFor();
 await reset({index:2,partial:true});await finish();await done();await banner().getByRole('heading',{name:'Workout saved',exact:true}).waitFor();assert.equal(await popup().count(),0);assert.equal(await page.getByRole('heading',{name:'KUDOS!',exact:true}).count(),0);assert.match(await banner().innerText(),/Next: Workout 1 of 3 · Push/);await page.getByRole('tab',{name:'History',exact:true}).click();await page.getByRole('tab',{name:'Schedule',exact:true}).click();assert.equal(await banner().count(),0);
 await reset({partial:true});await finish();await done();await banner().waitFor();await banner().getByRole('button',{name:'Dismiss workout acknowledgement',exact:true}).click();assert.equal(await banner().count(),0);await page.reload();await page.locator('.calendar').waitFor();assert.equal(await banner().count(),0);
 await reset({index:2,queued:true});await finish();await done();await popup().getByRole('heading',{name:'CYCLE COMPLETE',exact:true}).waitFor();await popup().getByText('Next: Workout 1 of 3 · New Push',{exact:true}).waitFor();await page.mouse.click(5,5);await popup().waitFor({state:'hidden'});
 // The selected glass pill follows all four tabs on mobile and desktop, including keyboard focus.
 for(const width of [320,390,982]){await page.setViewportSize({width,height:844});for(const name of ['Schedule','Programs','History','Settings']){await page.getByRole('tab',{name,exact:true}).click();const active=page.getByRole('tab',{name,exact:true});await page.waitForFunction(name=>{const tab=[...document.querySelectorAll('.mainnav [role=tab]')].find(e=>e.textContent===name);return tab&&getComputedStyle(tab).color==='rgb(255, 255, 255)'},name);assert.equal(await page.locator('.mainnav [data-state=active]').count(),1);assert.equal(await active.evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');assert.match(await active.evaluate(e=>getComputedStyle(e).backgroundImage),/59, 130, 246/);assert.equal(await page.locator('.mainnav').evaluate(e=>getComputedStyle(e).backdropFilter),'blur(24px) saturate(1.9)');assert.equal(await page.locator('.mainnav').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(255, 255, 255, 0.72)');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}if(width===390)await page.screenshot({path:'.sites-runtime/navigation-daylight-390.png',animations:'disabled'})}
 await page.emulateMedia({reducedMotion:'reduce'});await reset();await finish();await done();await popup().waitFor();assert.equal(await popup().locator('.celebration-ambient-glow').evaluate(e=>getComputedStyle(e).animationName),'none');await dismiss();
 const rounded=fixture({partial:true});rounded.session.exercises[0].sets[1].done=true;act(rounded,{type:'finishWorkout',confirmIncomplete:true},today,zone);assert.equal(workoutAcknowledgement(rounded,rounded.logs[0],today).kind,'saved');
 assert.deepEqual(errors,[]);console.log('PASS Summary → Done → one-time acknowledgement; full success, final cycle and queued version; partial/extra/skipped states; exact saved duration; dismiss/Esc/backdrop; leave/reload never replay; active program preserved; daylight glass modal; all 4 navigation tabs at 320/390/982px; reduced motion.');
}finally{await browser.close()}
