import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {initialState,act,clone,localDate}=await import('../.sites-runtime/tests/workout-domain.mjs');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});
let state=initialState(),revision=0,failSave=false;const errors=[],actions=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/training',async route=>{try{const request=route.request();if(request.method()==='POST'){const body=request.postDataJSON();actions.push(body.action.type);if(failSave&&body.action.type==='saveSession'){failSave=false;throw Error('Simulated save failure')}state=JSON.parse(JSON.stringify(act(state,body.action,localDate(),body.timezone)));revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const dialog=()=>page.getByRole('dialog');
const workout=()=>page.locator('.workout');
async function settled(){await page.waitForFunction(()=>!document.querySelector('.workout fieldset:disabled'))}
async function checkbox(n){await settled();await workout().getByRole('checkbox',{name:`Set ${n} completed`,exact:true}).click();await settled();await workout().getByText('Progress saved',{exact:true}).waitFor()}
async function entry(n,weight='70',reps='10'){await settled();await workout().getByRole('spinbutton',{name:`Set ${n} weight`,exact:true}).fill(weight);await workout().getByRole('spinbutton',{name:`Set ${n} reps`,exact:true}).fill(reps)}
try{
 await page.goto('http://127.0.0.1:5173/');await page.getByRole('heading',{name:'No active schedule'}).waitFor();await page.getByRole('tab',{name:'Programs',exact:true}).click();await page.getByRole('button',{name:'Create program',exact:true}).click();await dialog().getByRole('textbox',{name:'Program name',exact:true}).fill('Custom QA');await dialog().getByRole('button',{name:'Add exercise',exact:true}).click();await dialog().getByRole('combobox',{name:'Search exercise catalog'}).fill('Cable Y Raise');await page.getByText('No exercise found for “Cable Y Raise”',{exact:true}).waitFor();await page.getByRole('button',{name:'Create “Cable Y Raise”',exact:true}).click();assert.equal(await dialog().getByRole('textbox',{name:'Exercise name',exact:true}).inputValue(),'Cable Y Raise');await dialog().getByRole('textbox',{name:'Primary muscle (optional)'}).fill('Shoulders');await dialog().getByRole('textbox',{name:'Equipment (optional)'}).fill('Cable');await dialog().getByRole('textbox',{name:'Exercise library notes (optional)'}).fill('Reusable note');await dialog().getByRole('button',{name:'Save & add exercise'}).click();await dialog().getByRole('spinbutton',{name:'Cable Y Raise sets',exact:true}).waitFor();assert.equal(state.customExercises.length,1);assert.equal(state.customExercises[0].sets,undefined);assert.equal(await dialog().getByRole('textbox',{name:'Program name',exact:true}).inputValue(),'Custom QA');await dialog().getByRole('spinbutton',{name:'Cable Y Raise sets'}).fill('4');await dialog().getByRole('tab',{name:/^Day 3:/}).click();await dialog().getByRole('combobox',{name:'Day type',exact:true}).click();await page.getByRole('option',{name:'Rest day',exact:true}).click();await dialog().getByRole('button',{name:'Create program',exact:true}).click();await dialog().waitFor({state:'hidden'});const p=state.programs.at(-1),customId=state.customExercises[0].id;assert.equal(p.versions[0].days[0].exercises[0].exerciseId,customId);assert.equal(p.versions[0].days[0].exercises[0].sets,4);console.log('PASS create from search, preserve program draft, immediate prescription, independent identity');
 await page.reload();await page.getByRole('heading',{name:'No active schedule'}).waitFor();await page.getByRole('tab',{name:'Programs',exact:true}).click();await page.getByRole('button',{name:'Create program',exact:true}).click();await dialog().getByRole('button',{name:'Add exercise',exact:true}).click();await dialog().getByRole('combobox',{name:'Search exercise catalog'}).fill('Cable Y Raise');await page.getByRole('option',{name:/Cable Y Raise.*Custom/}).waitFor();await page.getByRole('option',{name:/Cable Y Raise.*Custom/}).click();await dialog().getByRole('spinbutton',{name:'Cable Y Raise sets'}).waitFor();await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await dialog().waitFor({state:'hidden'});await page.getByRole('tab',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Edit custom exercise Cable Y Raise'}).click();await page.getByRole('textbox',{name:'Exercise name',exact:true}).fill('Standing Cable Y Raise');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('heading',{name:'Standing Cable Y Raise',exact:true}).waitFor();assert.equal(state.customExercises[0].id,customId);await page.getByRole('button',{name:'Archive custom exercise Standing Cable Y Raise'}).click();await page.getByText('Your custom exercises will appear here.',{exact:true}).waitFor();await page.getByRole('button',{name:'Show archived exercises'}).click();await page.getByRole('button',{name:'Restore custom exercise Standing Cable Y Raise'}).click();await page.getByRole('button',{name:'Archive custom exercise Standing Cable Y Raise'}).waitFor();console.log('PASS reusable Custom search result after reload; edit, archive and restore stable identity');
 // Seed an isolated multi-exercise scheduled workout through the real action domain.
 act(state,{type:'duplicateProgram',id:state.programs[0].id},localDate(),'Asia/Bangkok');const presetCopy=state.programs.at(-1);presetCopy.versions[0].days[0].exercises=presetCopy.versions[0].days[0].exercises.slice(0,3);presetCopy.versions[0].days[0].exercises[0].rest=120;act(state,{type:'createSchedule',programId:presetCopy.id,versionId:presetCopy.versions[0].id,date:localDate()},localDate(),'Asia/Bangkok');act(state,{type:'startWorkout',date:localDate()},localDate(),'Asia/Bangkok');const plans=clone(state.programs);
 await page.reload();await workout().getByRole('heading',{name:'Bench Press',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Save progress',exact:true}).count(),0);
 await entry(1);await checkbox(1);assert.ok(Math.abs(state.session.timerEnd-Date.now()-120000)<2000);await workout().getByRole('timer').filter({hasText:/^02:00|01:59$/}).waitFor();assert.equal(await workout().locator('.setnext').getAttribute('data-set-id'),state.session.exercises[0].sets[1].id);await entry(2);await checkbox(2);assert.equal(state.session.timerSource.setId,state.session.exercises[0].sets[1].id);await checkbox(1);assert.ok(state.session.timerEnd);assert.equal(await workout().getByRole('spinbutton',{name:'Set 1 weight'}).inputValue(),'70');await checkbox(2);assert.equal(state.session.timerEnd,null);await checkbox(1);console.log('PASS Done atomic autosave, single timer, next-set focus, uncheck retains values and cancels correct timer');
 const beforeNext=clone(state.session.exercises);await workout().getByRole('button',{name:'Next exercise',exact:true}).click();await workout().getByRole('heading',{name:'Incline Dumbbell Press',exact:true}).waitFor();assert.deepEqual(state.session.exercises,beforeNext);await workout().getByRole('button',{name:'Skip exercise',exact:true}).click();await workout().getByRole('heading',{name:'Overhead Press',exact:true}).waitFor();assert.ok(state.session.exercises[1].sets.every(s=>s.skipped&&!s.done));assert.equal(state.session.timerEnd,null);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.ok(state.session.exercises[1].sets.every(s=>!s.skipped));await workout().locator('.exercise-nav').getByRole('button',{name:/Bench Press/}).click();await workout().getByRole('button',{name:'Skip exercise',exact:true}).click();await page.getByRole('alertdialog').getByRole('heading',{name:'Skip remaining sets?'}).waitFor();await page.getByRole('alertdialog').getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(state.session.exercises[0].skipped,false);await workout().getByRole('button',{name:'Skip exercise',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Skip remaining',exact:true}).click();await workout().getByRole('heading',{name:'Incline Dumbbell Press',exact:true}).waitFor();assert.ok(state.session.exercises[0].sets[0].done);assert.ok(state.session.exercises[0].sets.slice(1).every(s=>s.skipped));await workout().getByText('1 of 9 planned sets completed',{exact:true}).waitFor();console.log('PASS Next changes navigation only; skip 0 + Undo, partial confirmation preserves completed work and progress');
 failSave=true;await workout().getByRole('spinbutton',{name:'Set 1 weight'}).fill('42.5');await workout().getByRole('alert').filter({hasText:'Couldn’t save changes'}).waitFor();assert.equal(await workout().getByRole('spinbutton',{name:'Set 1 weight'}).inputValue(),'42.5');assert.equal(state.session.exercises[1].sets[0].weight,null);await workout().getByRole('button',{name:'Retry',exact:true}).click();await workout().getByText('Progress saved',{exact:true}).waitFor();assert.equal(state.session.exercises[1].sets[0].weight,42.5);await page.reload();await workout().getByRole('heading',{name:'Bench Press',exact:true}).waitFor();await workout().getByRole('button',{name:'Next exercise',exact:true}).click();assert.equal(await workout().getByRole('spinbutton',{name:'Set 1 weight'}).inputValue(),'42.5');console.log('PASS autosave failure retains input; Retry and reload persist it');
 await workout().getByRole('button',{name:'Add extra set',exact:true}).click();await workout().getByRole('spinbutton',{name:'Set 4 weight'}).waitFor();await entry(1,'42.5');await checkbox(1);await entry(2);await checkbox(2);await entry(3);await checkbox(3);assert.ok(state.session.timerEnd);await entry(4);await checkbox(4);assert.equal(state.session.timerEnd,null);await checkbox(4);await workout().getByRole('button',{name:'Remove extra set 4'}).click();await workout().getByRole('spinbutton',{name:'Set 4 weight'}).waitFor({state:'hidden'});assert.equal(state.session.exercises[1].sets.length,3);assert.deepEqual(state.programs,plans);console.log('PASS extra sets autosave, participate in rest, final completion clears timer and removal retains original plan');
 state.session.timerEnd=Date.now()+600;await page.reload();await workout().getByText('Rest complete. Ready for your next set.',{exact:true}).waitFor();assert.equal(await workout().getByRole('timer').innerText(),'00:00');await workout().getByRole('button',{name:'+30s',exact:true}).click();await settled();assert.ok(state.session.timerEnd>Date.now());await workout().getByRole('button',{name:'Skip rest',exact:true}).click();await settled();assert.equal(state.session.timerEnd,null);
 await workout().getByRole('button',{name:'Add exercise',exact:true}).click();await workout().getByRole('combobox',{name:'Search exercise catalog'}).fill('Standing Cable Y Raise');await page.getByRole('option',{name:/Standing Cable Y Raise.*Custom/}).click();await workout().getByRole('heading',{name:'Standing Cable Y Raise',exact:true}).waitFor();assert.equal(state.session.exercises.at(-1).exerciseId,customId);await workout().getByRole('button',{name:'Remove additional exercise',exact:true}).click();await workout().getByRole('heading',{name:'Bench Press',exact:true}).waitFor();console.log('PASS custom exercise selection adds and opens it in active workouts');
 for(const width of [320,375,390,430,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await workout().evaluate(e=>e.scrollWidth<=e.clientWidth),`${width}px workout overflow`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px page overflow`);assert.ok((await workout().getByRole('button',{name:'Start rest',exact:true}).boundingBox()).height>=44);await page.screenshot({path:`.sites-runtime/workout-${width}.png`,animations:'disabled'})}console.log('PASS completed rest clamps to zero, +30s / Skip; 320–1440px workout fit and touch targets');
 await workout().getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Confirm',exact:true}).click();await workout().waitFor({state:'hidden'});assert.equal(state.logs.at(-1).status,'PARTIALLY_COMPLETED');await page.getByRole('tab',{name:'History',exact:true}).click();assert.equal(await page.locator('.historysummary>div').nth(1).locator('b').innerText(),'4');assert.deepEqual(errors,[]);console.log('PASS partial finish/history retains every performed set; no browser runtime errors');
}catch(e){console.log((await page.locator('body').innerText()).slice(-4500));throw e}finally{await browser.close()}


