import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {build} from 'esbuild';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/vieta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build({stdin:{contents:"export * from './lib/cadence';export * from './lib/actions';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/tests/controls-domain.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});
const {initialState,act,clone,localDate}=await import('../.sites-runtime/tests/controls-domain.mjs'),today=localDate(),zone='Asia/Bangkok';let state=initialState(),revision=0;act(state,{type:'duplicateProgram',id:state.programs[0].id},today,zone);const program=state.programs.at(-1);act(state,{type:'createSchedule',programId:program.id,versionId:program.versions[0].id,date:today},today,zone);act(state,{type:'startWorkout',date:today},today,zone);const plans=clone(state.programs),schedules=clone(state.schedules),errors=[];
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'light'});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.__haptics=[];Object.defineProperty(navigator,'vibrate',{value:pattern=>{window.__haptics.push(pattern);return true}})});
await page.route('**/api/training',async route=>{try{if(route.request().method()==='POST'){const {action}=route.request().postDataJSON();const requestNow=await page.evaluate(()=>Date.now()),realNow=Date.now;try{Date.now=()=>requestNow;state=JSON.parse(JSON.stringify(act(clone(state),action,today,zone)))}finally{Date.now=realNow}revision++}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,revision})})}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:e.message})})}});
const workout=()=>page.locator('.workout'),dialog=()=>page.getByRole('alertdialog');async function saved(){await workout().getByText('Progress saved',{exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.workout fieldset:disabled'))}
async function resume(){await page.locator('.sessionbanner').getByRole('button',{name:'Resume workout',exact:true}).click();await workout().waitFor()}
try{
 await page.clock.install({time:new Date()});await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await saved();await workout().getByRole('spinbutton',{name:'Set 1 weight',exact:true}).fill('20');await workout().getByRole('spinbutton',{name:'Set 1 reps',exact:true}).fill('8');await workout().getByRole('checkbox',{name:'Set 1 completed',exact:true}).click();await saved();assert.ok(state.session.timerId);assert.ok(Math.abs(state.session.timerEnd-Date.now()-90000)<3000);assert.equal(await workout().locator('.exercise-nav .selected').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');assert.equal(await workout().locator('.exercise-nav .selected .exnumber').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');
 for(const width of [320,390,668,982]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await workout().locator('.compact-rest').evaluate(e=>getComputedStyle(e).position),'static');assert.ok((await workout().locator('.compact-rest').boundingBox()).height<145);for(const name of ['-15s','+15s','Skip rest']){const b=await workout().getByRole('button',{name,exact:true}).boundingBox();assert.ok(b.height>=44);assert.ok(b.x>=0&&b.x+b.width<=width)}if(width===390||width===982)await page.screenshot({path:`.sites-runtime/workout-controls-${width}.png`,animations:'disabled'})}
 await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:'.sites-runtime/workout-controls-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});await page.setViewportSize({width:390,height:844});await workout().getByRole('textbox',{name:'Workout notes',exact:true}).fill('Switching tabs keeps everything');await workout().getByRole('button',{name:'Add extra set',exact:true}).click();await saved();const before=clone(state.session);await page.evaluate(()=>dispatchEvent(new WheelEvent('wheel',{deltaY:4})));await page.getByRole('tab',{name:'History',exact:true}).click();await workout().waitFor({state:'hidden'});assert.deepEqual(state.session,before);assert.equal(state.logs.length,0);assert.deepEqual(state.schedules,schedules);assert.equal(await page.locator('.workout-exit').count(),0);await resume();assert.equal(await workout().getByRole('textbox',{name:'Workout notes',exact:true}).inputValue(),'Switching tabs keeps everything');
 let end=state.session.timerEnd;const period=state.session.timerId;await workout().getByRole('button',{name:'+15s',exact:true}).click();await saved();assert.equal(state.session.timerEnd,end+15000);await workout().getByRole('button',{name:'-15s',exact:true}).click();await saved();assert.equal(state.session.timerEnd,end);assert.equal(state.session.timerId,period);await workout().getByRole('button',{name:'Skip rest',exact:true}).click();await saved();assert.equal(state.session.timerEnd,null);
 await workout().getByRole('spinbutton',{name:'Rest seconds',exact:true}).fill('20');await workout().getByRole('button',{name:'Start rest',exact:true}).click();await saved();await page.clock.runFor(11000);assert.deepEqual(await page.evaluate(()=>window.__haptics),[25]);await workout().getByRole('button',{name:'+15s',exact:true}).click();await saved();await page.clock.runFor(15000);assert.deepEqual(await page.evaluate(()=>window.__haptics),[25]);await page.clock.runFor(10000);assert.deepEqual(await page.evaluate(()=>window.__haptics),[25,[80,40,120]]);await page.clock.runFor(5000);await page.evaluate(()=>dispatchEvent(new WheelEvent('wheel',{deltaY:4})));await page.getByRole('tab',{name:'History',exact:true}).click();await workout().waitFor({state:'hidden'});await resume();await page.clock.runFor(2000);assert.deepEqual(await page.evaluate(()=>window.__haptics),[25,[80,40,120]]);
 await workout().getByRole('button',{name:'Discard workout',exact:true}).click();await dialog().getByText('Your progress from this workout will be removed.',{exact:true}).waitFor();assert.equal(await dialog().getByRole('button',{name:'Keep workout',exact:true}).evaluate(e=>e===document.activeElement),true);const retained=clone(state.session);await dialog().getByRole('button',{name:'Keep workout',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.deepEqual(state.session,retained);await workout().getByRole('button',{name:'Discard workout',exact:true}).click();await dialog().getByRole('button',{name:'Discard workout',exact:true}).click();await workout().waitFor({state:'hidden'});assert.equal(state.session,null);assert.equal(state.logs.length,0);assert.deepEqual(state.programs,plans);assert.deepEqual(state.schedules,schedules);await page.getByRole('button',{name:'Start workout · Push',exact:true}).click();await workout().waitFor();assert.equal(state.session.exercises[0].sets.length,3);assert.ok(state.session.exercises.every(e=>e.sets.every(s=>!s.done&&!s.skipped&&s.weight===null&&s.reps===null)));assert.equal(state.session.notes,'');
 assert.deepEqual(errors,[]);console.log('PASS compact non-sticky timer and glass/contrast states 320–982px; automatic rest and ±15s/Skip; once-only 10s/0s haptics across adjustments and resume; Tab switch preserves session; Discard removes only session and restarts the same clean workout.');
}finally{await browser.close()}
