"use client";
import {useEffect,useRef,useState,useCallback} from 'react';
import Image from 'next/image';
import {CalendarDays,Dumbbell,History,Settings,Plus,ChevronLeft,ChevronRight,Moon,Check,Play,Copy,Archive,Edit3,Repeat2,Timer,RefreshCw,SlidersHorizontal,Square} from 'lucide-react';
import MainNavigation from './main-navigation';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import LoadingScreen from './loading-screen';
import StopProgramDialog from './stop-program-dialog';
import {cardLabel} from '@/lib/display-label';
import {prescriptionSummary} from '@/lib/prescription';
import {Toaster,toast} from 'sonner';
import {State,Program,Version,Log,Exercise,CustomExerciseInput,exerciseLibrary,localDate,addDays,dateLabel,activeSchedule,projection,statusFor,getVersion,clone,currentProgram,workoutDays} from '@/lib/cadence';
import {Choice,Field,CycleStrip} from './training-controls';
import PlannedExerciseDetails from './planned-exercise-details';
import ProgramEditor from './program-editor';
import WorkoutEditor from './workout-editor';
import RestNotificationsSetting from './rest-notifications-setting';
import PersonalExerciseLibrary from './personal-exercise-library';
import ProgramChooser from './program-chooser';
import HistoryWorkoutCard from './history-workout-card';
import HistoryToolbar from './history-toolbar';
import HistoryWorkoutDetail from './history-workout-detail';
import ManageProgram from './manage-program';
import ProgramSchedule from './program-schedule';
import SchedulePostWorkout from './schedule-post-workout';
import {workoutAcknowledgement,type WorkoutAcknowledgement} from '@/lib/workout-acknowledgement';
import {useMobileLayout} from '@/hooks/use-mobile-layout';
type Modal={type:'choose'|'create'|'apply'|'edit'|'program'|'log'|'rename'|'changeWorkout';id?:string;versionId?:string;onboard?:boolean};
export default function CadenceApp(){
 const mobile=useMobileLayout();
 const [workoutScreenOpen,setWorkoutScreenOpen]=useState(true);
 const [historyFiltersOpen,setHistoryFiltersOpen]=useState(false);
 const [workoutSummaryId,setWorkoutSummaryId]=useState<string|null>(null);
 const [acknowledgement,setAcknowledgement]=useState<WorkoutAcknowledgement|null>(null);
 const [historyId,setHistoryId]=useState<string|null>(null),historyScroll=useRef(0);
 const [data,setData]=useState<{state:State;revision:number}|null>(null),[tab,setTab]=useState('Schedule'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[today,setToday]=useState(''),[date,setDate]=useState(''),[modal,setModal]=useState<Modal|null>(null),[confirmation,setConfirmation]=useState<{title:string;body:string;action:any}|null>(null),[archived,setArchived]=useState(false),[filter,setFilter]=useState('All'),[historySearch,setHistorySearch]=useState(''),[historyFrom,setHistoryFrom]=useState(''),[historyTo,setHistoryTo]=useState(''),[unit,setUnit]=useState('kg'),[rest,setRest]=useState(90);
 const dataRef=useRef(data),locked=useRef(false),draftRef=useRef<any>(null),flushDraftRef=useRef<(()=>Promise<boolean>)|null>(null),pendingSessionSave=useRef<Promise<void>|null>(null); const recordDraft=useCallback((a:any,flush?:()=>Promise<boolean>)=>{draftRef.current=dataRef.current?.state.session?a:null;flushDraftRef.current=dataRef.current?.state.session&&flush?flush:null},[]);const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 async function load(){try{const r=await fetch('/api/training',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);dataRef.current=d;setData(d);setUnit(d.state.settings.unit);setRest(d.state.settings.defaultRest);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load training data.')}}
 useEffect(()=>{setToday(localDate());setDate(localDate());void load();const t=setInterval(()=>setToday(localDate()),30000);return()=>clearInterval(t)},[]);
 function confirm(title:string,body:string,action:any){setConfirmation({title,body,action})}
 async function run(action:any){while(pendingSessionSave.current)await pendingSessionSave.current;if(action.type==='saveSession'&&(!dataRef.current?.state.session||action.id!==dataRef.current.state.session.id))return false;if(action.type==='endSchedule'&&draftRef.current&&!(flushDraftRef.current?await flushDraftRef.current():await run(draftRef.current)))return false;if(locked.current||!dataRef.current)return false;locked.current=true;const background=action.type==='saveSession';let releaseSave=()=>{};if(background)pendingSessionSave.current=new Promise<void>(resolve=>{releaseSave=resolve});else setBusy(true);try{const r=await fetch('/api/training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:dataRef.current.revision,timezone,action})});const result:any=await r.json();if(!r.ok){toast.error(result.error);if(result.code==='CONFLICT')await load();return false}dataRef.current=result;if(action.type==='startWorkout'){setWorkoutScreenOpen(true);setWorkoutSummaryId(null);setTab('Schedule')}if(action.type==='deleteLog'){setHistoryId(null);setWorkoutSummaryId(null);setModal(null);setTab('History');requestAnimationFrame(()=>window.scrollTo({top:historyScroll.current,behavior:'instant'}))}if(action.type==='discardWorkout'){setWorkoutScreenOpen(false);setWorkoutSummaryId(null);setTab('Schedule');setDate(today)}if(!result.state.session){draftRef.current=null;flushDraftRef.current=null;}setData(result);setError('');if(action.type==='finishWorkout'){setWorkoutSummaryId(result.state.logs.at(-1)?.id||null);setTab('Schedule');setModal(null);setConfirmation(null)}if(!['saveSession','timer','finishWorkout'].includes(action.type))toast.success(({saveProgram:'Program saved',createSchedule:'Program started',applyVersion:action.mode==='AFTER_CYCLE'?'Version queued':'Program version applied',changeWorkout:'Current workout changed',skipWorkout:'Workout skipped',override:'Schedule updated',finishWorkout:'Workout saved to history',discardWorkout:'Workout discarded',deleteLog:'Workout deleted',correctLog:'Historical correction saved',settings:'Preferences saved',endSchedule:'Schedule stopped'} as any)[action.type]||'Saved');return true}catch(e){toast.error('Could not save. Your input is still here; please try again.');return false}finally{locked.current=false;if(background){pendingSessionSave.current=null;releaseSave()}else setBusy(false)}}
 async function createCustomExercise(input:CustomExerciseInput){if(!await run({type:'createCustomExercise',...input}))return null;return dataRef.current!.state.customExercises.at(-1)!}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_cadence_schedule',title:'Read workout schedule',description:'Read recorded workout history for a past date, or the current next workout for today. Future dates have no assignments.',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(typeof input?.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!Number.isFinite(Date.parse(input.date)))throw Error('Invalid date');if(!dataRef.current)throw Error('Training data is unavailable');const o=projection(dataRef.current.state,input.date);return{date:input.date,occurrence:o,status:statusFor(dataRef.current.state,o,localDate())}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 async function changeTab(next:string){if(flushDraftRef.current&&!await flushDraftRef.current())return;setHistoryId(null);setWorkoutSummaryId(null);setTab(next)} useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(draftRef.current){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard)},[]); const s=data?.state,sch=s?activeSchedule(s):null,currentApp=s?currentProgram(s,today||localDate()).application:null;
 async function chooseProgram(p:Program){let id=p.id;if(p.preset){if(!await run({type:'duplicateProgram',id}))return;id=dataRef.current!.state.programs.at(-1)!.id}setModal({type:sch?'program':'create',id})}
 function openHistory(id:string){historyScroll.current=window.scrollY;setHistoryId(id)}
 function backHistory(){const id=historyId;setHistoryId(null);requestAnimationFrame(()=>{window.scrollTo({top:historyScroll.current,behavior:'instant'});document.querySelector<HTMLButtonElement>(`[data-history-id="${id}"]`)?.focus({preventScroll:true})})}
 const filteredHistory=s?s.logs.filter(l=>(filter==='All'||l.status===filter)&&(!historyFrom||l.date>=historyFrom)&&(!historyTo||l.date<=historyTo)&&(l.name+' '+(l.occurrence?.programName||'')+' '+l.exercises.map(e=>e.name).join(' ')).toLowerCase().includes(historySearch.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||b.finishedAt.localeCompare(a.finishedAt)):[];
 const selectedHistoryLog=s?.logs.find(l=>l.id===historyId),workoutSummaryLog=s?.logs.find(l=>l.id===workoutSummaryId);
 useEffect(()=>{if(tab!=='Schedule'||workoutSummaryId||s?.session?.id)setAcknowledgement(null)},[tab,workoutSummaryId,s?.session?.id]);
 function doneSummary(){if(s&&workoutSummaryLog)setAcknowledgement(workoutAcknowledgement(s,workoutSummaryLog,today));setWorkoutSummaryId(null);setDate(today);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}))}
 const chosenProgram=s?.programs.find(p=>p.id===modal?.id),chosenLog=s?.logs.find(l=>l.id===modal?.id);

 if(!s&&!error)return <LoadingScreen/>;
 return <main className={'shell'+(tab==='Schedule'?' schedule-view':tab==='History'?' history-view':'')+(tab==='Schedule'&&s?.session&&workoutScreenOpen?' workout-view':'')}><Toaster richColors position="top-center"/><header><div className="brand"><Image src="/cadence-mark.png" width={40} height={40} alt="" className="brand-icon" unoptimized/><b>Cadence</b></div><div className="row"><span className="muted header-date">{today&&dateLabel(today,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}</span></div></header><MainNavigation tab={tab} onChange={changeTab}/>
 {!s?<section className="panel loading">{error?<><h2>Unable to open your training data</h2><p className="muted">{error}</p><a className="primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a><button className="secondary" onClick={load}><RefreshCw size={18}/>Try again</button></>:<LoadingScreen/>}</section>:<>
 {s.session&&!(tab==='Schedule'&&workoutScreenOpen)&&<div className="sessionbanner"><div><Play size={18}/><b>{s.session.name}</b><span>Workout in progress · {dateLabel(s.session.date)}</span></div><button onClick={()=>{setWorkoutScreenOpen(true);setTab('Schedule');setModal(null)}}>Resume workout</button></div>}
 {!(tab==='History'&&selectedHistoryLog)&&!(tab==='Schedule'&&workoutSummaryLog)&&<section className="pagehead"><div><p className="eyebrow">{tab==='Schedule'?'YOUR TRAINING':tab==='Programs'?'YOUR TRAINING PLANS':tab==='History'?'YOUR ACTUAL TRAINING':'YOUR PREFERENCES'}</p><h1>{tab==='Schedule'&&!sch?'No active program':tab}</h1></div>{tab==='Schedule'&&sch?<div className="schedule-head-controls"><div className="schedule-head-actions"><button className="secondary" onClick={()=>setModal({type:'apply'})}><SlidersHorizontal size={18}/>Manage program</button><button type="button" className="stop-program" disabled={busy} onClick={()=>confirm('Stop program?',s.session?'Your active workout and rest timer will stop now. Recorded results will be saved to History. Your saved programs and workout history will be kept.':'Your active program will stop. Your saved programs and workout history will be kept.',{type:'endSchedule',date:today,confirmed:true,stopActiveWorkout:true})}><span className="stop-program-icon" aria-hidden="true"><Square size={12} fill="currentColor" strokeWidth={0}/></span>Stop program</button></div></div>:tab==='Programs'?<button className="primary" onClick={()=>setModal({type:'edit'})}><Plus size={18}/>Create program</button>:null}</section>}
 {tab==='Schedule'&&workoutSummaryLog&&<HistoryWorkoutDetail state={s} log={workoutSummaryLog} summary onBack={doneSummary} onEdit={()=>setModal({type:'log',id:workoutSummaryLog.id})}/>}
 {tab==='Schedule'&&!workoutSummaryLog&&(s.session&&workoutScreenOpen?<section className="panel"><WorkoutEditor key={s.session.id} state={s} value={s.session} busy={busy} run={run} confirm={confirm} onDraft={recordDraft} onCreateCustom={createCustomExercise}/></section>:<>
 {acknowledgement&&<SchedulePostWorkout acknowledgement={acknowledgement} onDismiss={()=>setAcknowledgement(null)}/>}
 <ProgramSchedule state={s} today={today} date={date} onDate={setDate} busy={busy} run={run} mobile={mobile} onChoose={()=>setModal({type:'choose'})} onCreate={()=>setModal({type:'edit',onboard:true})} onChangeWorkout={()=>setModal({type:'changeWorkout'})} onSkipWorkout={name=>confirm(`Skip ${name}?`,`${name} will be marked as skipped for this cycle. The next workout will become current.\n\nYour program will not be changed.`,{type:'skipWorkout',confirmed:true})} onResume={()=>setWorkoutScreenOpen(true)} onReview={log=>{historyScroll.current=0;setTab('History');setHistoryId(log.id)}}/></>)}
 {tab==='Programs'&&<><div className="row between sectionline"><p className="muted">Build your workout sequence. Train at your own pace.</p><button className="textbtn" onClick={()=>setArchived(!archived)}>{archived?'Show available programs':'Archived programs'}</button></div><h3 className="previewtitle">Your programs</h3><div className="programgrid">{s.programs.filter(p=>!p.preset&&p.archived===archived).map(p=>{const v=p.versions.at(-1)!;return <section className="panel programcard" key={p.id}><div className="row between"><div className="programicon"><Dumbbell/></div>{currentApp?.programId===p.id&&<span className="badge program-active"><Check size={15} aria-hidden="true"/>Active</span>}</div><h2 title={p.name} aria-label={p.name}>{cardLabel(p.name,30)}</h2><p className="muted">{p.description}</p><div className="programstats"><b>{workoutDays(v.days).length}<span>Workouts per cycle</span></b></div><CycleStrip days={workoutDays(v.days)} labelLimit={10}/><div className="row between cardfooter"><span className="muted">Version {v.number}</span><button className="secondary" onClick={()=>setModal({type:'program',id:p.id})}>View program</button></div></section>})}</div>{!s.programs.some(p=>!p.preset&&p.archived===archived)&&<section className="panel restmessage">{archived?'No archived programs.':'Your own programs will appear here.'}</section>}{!archived&&<ProgramChooser state={s} busy={busy} onSelect={chooseProgram} onlyPresets/>}</>}
 {tab==='History'&&(selectedHistoryLog?<HistoryWorkoutDetail state={s} log={selectedHistoryLog} onBack={backHistory} onEdit={()=>setModal({type:'log',id:selectedHistoryLog.id})} onDelete={()=>confirm('Delete workout?','This workout and its recorded results will be permanently removed from History. Your program progress will stay unchanged.',{type:'deleteLog',id:selectedHistoryLog.id,confirmed:true})}/>:<><div className="historysummary grid grid-cols-3 gap-3"><div><b>{s.logs.length}</b><span>Workouts logged</span></div><div><b>{s.logs.reduce((n,l)=>n+l.exercises.reduce((n,e)=>n+e.sets.filter(x=>x.done).length,0),0)}</b><span>Sets completed</span></div><div><b>{Math.round(s.logs.reduce((n,l)=>n+(Date.parse(l.finishedAt)-Date.parse(l.startedAt))/60000,0))}</b><span>Minutes trained</span></div></div><HistoryToolbar open={historyFiltersOpen} onToggle={()=>setHistoryFiltersOpen(!historyFiltersOpen)} busy={busy} hasSession={!!s.session} onAdd={()=>{if(s.session){setWorkoutScreenOpen(true);setTab('Schedule')}else confirm('Start unscheduled workout?','Start a workout outside your program. It will appear in History when you finish.',{type:'startWorkout',date:today,unscheduled:true})}}><div className="row historyfilters"><input aria-label="Search workout history" placeholder="Search workouts or exercises" value={historySearch} onChange={e=>setHistorySearch(e.target.value)}/><Choice label="Completion filter" value={filter} onChange={setFilter} options={['All','COMPLETED','PARTIALLY_COMPLETED','UNSCHEDULED'].map(x=>({value:x,label:x==='All'?'All workouts':x==='PARTIALLY_COMPLETED'?'Partial':x==='UNSCHEDULED'?'Unscheduled':'Completed'}))}/><Field label="From"><input type="date" value={historyFrom} onChange={e=>setHistoryFrom(e.target.value)}/></Field><Field label="To"><input type="date" value={historyTo} onChange={e=>setHistoryTo(e.target.value)}/></Field></div></HistoryToolbar><div className="historylist">{filteredHistory.map(l=><HistoryWorkoutCard key={l.id} state={s} log={l} onOpen={()=>openHistory(l.id)}/>)}</div>{s.logs.length>0&&filteredHistory.length===0&&<p className="history-no-results">No workouts match your filters.</p>}{!s.logs.length&&<section className="panel welcome"><div className="iconplate"><History/></div><h2>Your training story starts here.</h2><p className="muted">Finish a workout to add your first log.</p><button className="primary" onClick={()=>setTab('Schedule')}>Open schedule</button></section>}</>)}
 {tab==='Settings'&&<div className="settingsgrid"><section className="panel"><h2>Training preferences</h2><p className="muted">Applied to workout entry and display.</p><div className="row"><Field label="Weight unit"><Choice label="Weight unit" value={unit} onChange={setUnit} options={[{value:'kg',label:'Kilograms (kg)'},{value:'lb',label:'Pounds (lb)'}]}/></Field><Field label="Default rest (seconds)"><input type="number" min={0} max={3600} value={rest} onChange={e=>setRest(Number(e.target.value))}/></Field></div><button className="primary" disabled={busy} onClick={()=>run({type:'settings',unit,defaultRest:rest})}>Save preferences</button></section><RestNotificationsSetting/><section className="panel"><h2>Program history</h2>{s.schedules.length?s.schedules.slice().reverse().map(x=><div className="schedulehistory" key={x.id}><b>{getVersion(s,x.applications[0].programId).program?.name}</b><p className="muted">{dateLabel(x.start)}{x.end?` – ${dateLabel(x.end)}`:''} · {x.status.toLowerCase()}</p></div>):<p className="muted">No programs started yet.</p>}</section><PersonalExerciseLibrary state={s} busy={busy} run={run} onCreate={createCustomExercise}/></div>}
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal(null)}}><DialogContent className={'trainingdialog'+(modal?.type==='edit'?' program-dialog':modal?.type==='apply'||modal?.type==='create'?' manage-program-dialog':'')} showCloseButton={!busy}><DialogTitle>{({choose:'Choose or create program',create:'Start program',apply:'Manage program',edit:chosenProgram?'Edit program':'Create program',program:'Program details',log:'Workout log',rename:'Program information',changeWorkout:'Change current workout'} as any)[modal?.type||'create']}</DialogTitle><DialogDescription>{modal?.type==='choose'?'Choose a preset to save your own copy, or create a program.':modal?.type==='log'?'Review the original plan and actual results.':modal?.type==='edit'?'Build your workouts in the order they repeat.':modal?.type==='changeWorkout'?'Adjust your position in this cycle. The previous workout will not be marked as skipped.':'Changes are saved only when you confirm.'}</DialogDescription>{modal?.type==='choose'&&<ProgramChooser state={s} busy={busy} onSelect={chooseProgram} onCreate={()=>setModal({type:'edit',onboard:true})}/>} {modal&&(modal.type==='create'||modal.type==='apply')&&<ManageProgram initialProgramId={modal.id} initialVersionId={modal.versionId} state={s} today={today} kind={modal.type} busy={busy} run={run} onDone={()=>{setModal(null);setTab('Schedule');setDate(today)}}/>}{modal?.type==='changeWorkout'&&<ChangeWorkoutDialog state={s} today={today} busy={busy} run={run} onDone={()=>setModal(null)}/>}{modal?.type==='edit'&&<ProgramEditor key={modal.id||'new'} program={chosenProgram} exercises={exerciseLibrary(s)} onCreateCustom={createCustomExercise} unit={s.settings.unit} defaultRest={s.settings.defaultRest} busy={busy} cycleLocked={!!sch?.applications.some(a=>a.programId===chosenProgram?.id)||sch?.cycleState?.queued?.programId===chosenProgram?.id} context={modal.onboard?'onboarding':'standalone'} onCancel={()=>setModal(modal.onboard?{type:'choose'}:null)} onSave={async a=>{const ok=await run(a);if(ok){const id=a.id||dataRef.current!.state.programs.at(-1)!.id;setModal(modal.onboard?{type:'create',id}:null);if(!modal.onboard){setTab('Programs');setArchived(false)}}return ok}}/>}{modal?.type==='program'&&chosenProgram&&<ProgramDetail state={s} program={chosenProgram} busy={busy} run={run} open={setModal}/>} {modal?.type==='rename'&&chosenProgram&&<RenameProgram program={chosenProgram} busy={busy} run={run} onDone={()=>setModal({type:'program',id:chosenProgram.id})}/>} {modal?.type==='log'&&chosenLog&&<WorkoutEditor state={s} value={chosenLog} busy={busy} run={run} confirm={confirm} history/>}</DialogContent></Dialog>
 <StopProgramDialog open={confirmation?.title==='Stop program?'} body={confirmation?.body||''} busy={busy} onClose={()=>{if(!busy)setConfirmation(null)}} onConfirm={async()=>{if(confirmation&&await run(confirmation.action)){setConfirmation(null);setModal(null)}}}/><AlertDialog open={!!confirmation&&confirmation.title!=='Stop program?'} onOpenChange={open=>{if(!open)setConfirmation(null)}}><AlertDialogContent className={confirmation?.action.type==='skipWorkout'?'skip-workout-dialog':confirmation?.action.type==='finishWorkout'?'finish-workout-dialog':confirmation?.action.type==='discardWorkout'?'discard-workout-dialog':confirmation?.action.type==='deleteLog'?'delete-workout-dialog':confirmation?.action.type==='startWorkout'?'start-workout-dialog':undefined}><AlertDialogTitle>{confirmation?.title}</AlertDialogTitle><AlertDialogDescription className="whitespace-pre-line">{confirmation?.body}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>{confirmation?.action.type==='finishWorkout'?'Keep training':confirmation?.action.type==='discardWorkout'?'Keep workout':confirmation?.action.type==='deleteLog'?'Keep workout':confirmation?.action.type==='startWorkout'?'Keep browsing':confirmation?.action.type==='skipWorkout'?'Keep workout':'Cancel'}</AlertDialogCancel><button disabled={busy} className="primary" onClick={async()=>{const a=confirmation!.action;if(await run(a)){setConfirmation(null);if(['applyVersion','override','endSchedule','discardWorkout','skipWorkout'].includes(a.type))setModal(null)}}}>{confirmation?.action.type==='finishWorkout'?'Finish workout':confirmation?.action.type==='discardWorkout'?'Discard workout':confirmation?.action.type==='deleteLog'?'Delete workout':confirmation?.action.type==='startWorkout'?'Start workout':confirmation?.action.type==='skipWorkout'?'Skip workout':'Confirm'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>}
 </main>
}
function ChangeWorkoutDialog({state,today,busy,run,onDone}:{state:State;today:string;busy:boolean;run:(action:Record<string,unknown>)=>Promise<boolean>;onDone:()=>void}){const current=currentProgram(state,today),workouts=current.workouts,index=current.cursor?.index||0,[selected,setSelected]=useState(index),skipped=new Set((current.schedule?.skippedWorkouts||[]).filter(item=>item.occurrence.appId===current.cursor?.appId&&item.occurrence.cycleNumber===current.cursor?.cycleNumber).map(item=>Number(item.occurrence.id.split(':workout:').at(-1))));return <div className="change-workout-dialog"><p className="muted">Current: {workouts[index]?.name}</p><fieldset disabled={busy}><legend>Choose workout</legend>{workouts.map((day,i)=><label key={i}><input type="radio" name="change-cycle-position" checked={selected===i} disabled={skipped.has(i)} onChange={()=>setSelected(i)}/><span>{day.name}{skipped.has(i)?' · Skipped this cycle':''}</span></label>)}</fieldset><p className="muted">Changing the current workout only adjusts your position in this cycle. It does not mark {workouts[index]?.name} as skipped.</p><div className="row wrap"><button type="button" className="secondary" disabled={busy} onClick={onDone}>Cancel</button><button type="button" className="primary" disabled={busy||selected===index||skipped.has(selected)} onClick={async()=>{if(await run({type:'changeWorkout',index:selected}))onDone()}}>Apply</button></div></div>}

function ProgramDetail({state,program:p,busy,run,open}:{state:State;program:Program;busy:boolean;run:(a:any)=>Promise<boolean>;open:(m:Modal)=>void}){const [vid,setVid]=useState(p.versions.at(-1)!.id),[day,setDay]=useState('0');const raw=p.versions.find(x=>x.id===vid)!,v={...raw,days:workoutDays(raw.days)},d=v.days[Number(day)];return <div><div className="row between"><div><h2>{p.name}</h2><p className="muted">{p.description}</p></div><Choice label="View version" value={vid} onChange={x=>{setVid(x);setDay('0')}} options={p.versions.map(x=>({value:x.id,label:`Version ${x.number}`}))}/></div><CycleStrip days={v.days}/><Tabs value={day} onValueChange={setDay}><TabsList className="daytabs">{v.days.map((x,i)=><TabsTrigger key={i} value={String(i)}>Workout {i+1}</TabsTrigger>)}</TabsList></Tabs><h3 className="previewtitle">{d.name}</h3>{d.notes&&<p className="planned-workout-notes">{d.notes}</p>}<div className="planlist">{d.exercises.map((e,i)=><div key={e.id}><span className="exnumber">{i+1}</span><div><b>{e.name}</b><p className="muted">{prescriptionSummary(e,state.settings.unit)}</p>{e.notes&&<p className="muted planned-exercise-notes">{e.notes}</p>}<PlannedExerciseDetails exercise={e} unit={state.settings.unit}/></div></div>)}</div><div className="row wrap management"><button className="primary" disabled={busy||p.archived} onClick={()=>open({type:activeSchedule(state)?'apply':'create',id:p.id,versionId:vid})}>Use this program</button><button className="secondary" disabled={busy||p.archived} onClick={()=>open({type:'edit',id:p.id})}><Edit3 size={16}/>Edit cycle</button><button className="secondary" onClick={()=>open({type:'rename',id:p.id})}>Edit information</button><button className="secondary" disabled={busy} onClick={()=>run({type:'duplicateProgram',id:p.id})}><Copy size={16}/>Duplicate</button><button className="textbtn" disabled={busy} onClick={async()=>{if(await run({type:'archiveProgram',id:p.id,archived:!p.archived}))open({type:'program',id:p.id})}}><Archive size={16}/>{p.archived?'Restore':'Archive'}</button></div><p className="muted footnote">Cycle edits create a version. Apply your chosen version from Manage program.</p></div>}
function RenameProgram({program:p,busy,run,onDone}:{program:Program;busy:boolean;run:(a:any)=>Promise<boolean>;onDone:()=>void}){const [name,setName]=useState(p.name),[description,setDescription]=useState(p.description);return <form onSubmit={async e=>{e.preventDefault();if(await run({type:'renameProgram',id:p.id,name,description}))onDone()}}><Field label="Program name"><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Description"><textarea value={description} maxLength={500} onChange={e=>setDescription(e.target.value)}/></Field><button className="primary" disabled={busy}>Save information</button></form>}
