"use client";
import {useRef,useState} from 'react';
import {ChevronDown,ChevronUp,Dumbbell,Trash2,Plus,Copy} from 'lucide-react';
import {uid,type PlanExercise,type SetPrescription} from '@/lib/cadence';
import {displayWeight,storedWeight,weightMultiplier,plannedSets,prescriptionSummary,prescriptionError,EXERCISE_NOTES_LIMIT} from '@/lib/prescription';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {Choice,Field} from './training-controls';

type Props={exercise:PlanExercise;order:number;total:number;open:boolean;onOpenChange:(open:boolean)=>void;onChange:(patch:Partial<PlanExercise>)=>void;onMove:(offset:number)=>void;onRemove:()=>void};
function RepFields({set,label,onChange}:{set:SetPrescription;label:string;onChange:(patch:Partial<SetPrescription>)=>void}){
 const range=set.repMin!==set.repMax;
 return <div className="set-rep-fields"><Field label="Target reps"><Choice label={`${label} rep type`} value={range?'range':'fixed'} onChange={value=>onChange({repMax:value==='fixed'?set.repMin:set.repMin+2})} options={[{value:'fixed',label:'Fixed reps'},{value:'range',label:'Rep range'}]}/></Field><div className="set-rep-inputs"><input type="number" required min={1} max={999} step={1} inputMode="numeric" aria-label={`${label} ${range?'minimum':'target'} reps`} value={set.repMin||''} onChange={e=>onChange({repMin:Number(e.target.value),...(!range?{repMax:Number(e.target.value)}:{})})}/>{range&&<><span aria-hidden="true">–</span><input type="number" required min={set.repMin||1} max={999} step={1} inputMode="numeric" aria-label={`${label} maximum reps`} value={set.repMax||''} onChange={e=>onChange({repMax:Number(e.target.value)})}/></>}</div></div>;
}
function RestFields({set,label,onChange}:{set:SetPrescription;label:string;onChange:(patch:Partial<SetPrescription>)=>void}){
 const range=set.restSecondsMax!==undefined;
 return <div className="planned-rest-fields"><Field label={range?'Rest min (seconds)':'Rest (seconds)'}><input type="number" required min={0} max={3600} step={1} inputMode="numeric" aria-label={`${label} rest seconds`} value={set.restSeconds} onChange={event=>onChange({restSeconds:Number(event.target.value)})}/></Field>{range&&<Field label="Rest max (seconds)"><input type="number" required min={set.restSeconds} max={3600} step={1} inputMode="numeric" aria-label={`${label} maximum rest seconds`} value={set.restSecondsMax} onChange={event=>onChange({restSecondsMax:Number(event.target.value)})}/></Field>}<button type="button" className="textbtn small" aria-label={`${label} ${range?'use fixed rest':'use rest range'}`} onClick={()=>onChange({restSecondsMax:range?undefined:Math.min(3600,set.restSeconds+30)})}>{range?'Use fixed rest':'Use a rest range'}</button></div>;
}
export default function ExercisePrescriptionCard({exercise:e,order,total,open,onOpenChange,onChange,onMove,onRemove}:Props){
 const sets=plannedSets(e),error=prescriptionError(e),trigger=useRef<HTMLButtonElement>(null);
 const [showError,setShowError]=useState(false),[bulk,setBulk]=useState(()=>({...sets[0]}));
 function saveSets(next:SetPrescription[]){onChange({sets:next.map((s,i)=>({...s,setNumber:i+1}))})}
 function update(id:string,patch:Partial<SetPrescription>){saveSets(sets.map(s=>s.id===id?{...s,...patch}:s))}
 function add(){const previous=sets.at(-1)!;saveSets([...sets,{...previous,id:uid(),setNumber:sets.length+1}])}
 return <Collapsible open={open} onOpenChange={onOpenChange} className="prescription-card">
  <CollapsibleTrigger ref={trigger} type="button" className="prescription-summary" aria-label={`Edit ${e.name} prescription`}>
   <Dumbbell size={18} aria-hidden="true"/><span><b>{order}. {e.name}</b><small>{prescriptionSummary(e)}</small>{e.groupId&&<small>Superset {e.groupId}{e.groupOrder?` · Position ${e.groupOrder}`:''}</small>}{e.notes&&<small className="prescription-note">Note: {e.notes}</small>}</span><ChevronDown className={open?'expanded':''} size={20} aria-hidden="true"/>
  </CollapsibleTrigger>
  <CollapsibleContent className="prescription-content">
   <details className="planned-bulk"><summary>Apply to all sets</summary><div className="planned-target-fields"><RepFields set={bulk} label={`${e.name} bulk`} onChange={patch=>setBulk({...bulk,...patch})}/><RestFields set={bulk} label={`${e.name} bulk`} onChange={patch=>setBulk({...bulk,...patch})}/></div><button type="button" className="secondary small" onClick={()=>saveSets(sets.map(s=>({...s,repMin:bulk.repMin,repMax:bulk.repMax,restSeconds:bulk.restSeconds,restSecondsMax:bulk.restSecondsMax})))}>Apply reps and rest to all sets</button><small className="muted">Weights and notes stay as entered. Customize any set afterward.</small></details>
   <ol className="planned-set-list" aria-label={`${e.name} planned sets`}>{sets.map((set,i)=>{const label=`${e.name} set ${i+1}`,unit=set.weightUnit||'kg';return <li className="planned-set-card" key={set.id}>
    <div className="row between"><b>Set {i+1}</b><button type="button" className="iconbtn danger" disabled={sets.length===1} aria-label={`Remove ${label}`} onClick={()=>saveSets(sets.filter(s=>s.id!==set.id))}><Trash2 size={17}/></button></div>
    <div className="planned-target-fields"><RepFields set={set} label={label} onChange={patch=>update(set.id,patch)}/><div className="planned-set-weight"><Field label="Weight (optional)"><input type="number" min={0} max={2000*weightMultiplier(unit)} step="any" inputMode="decimal" aria-label={`${label} target weight`} value={set.targetWeight===undefined?'':displayWeight(set.targetWeight,unit)} placeholder="No target" onChange={event=>update(set.id,{targetWeight:event.target.value===''?undefined:storedWeight(Number(event.target.value),unit)})}/></Field><Choice label={`${label} weight unit`} value={unit} onChange={value=>update(set.id,{weightUnit:value as 'kg'|'lb'})} options={[{value:'kg',label:'kg'},{value:'lb',label:'lb'}]}/></div><RestFields set={set} label={label} onChange={patch=>update(set.id,patch)}/></div>
    <details className="planned-set-extras" open={set.notes||set.targetRpe!==undefined?true:undefined}><summary>Set notes &amp; RPE (optional)</summary><div className="planned-metadata"><Field label="Set notes"><textarea rows={2} maxLength={EXERCISE_NOTES_LIMIT} aria-label={`${label} notes`} value={set.notes||''} placeholder="For example: dropset on this set" onChange={event=>update(set.id,{notes:event.target.value})}/></Field><Field label="Target RPE"><input type="number" min={1} max={10} step={0.5} inputMode="decimal" aria-label={`${label} target RPE`} value={set.targetRpe??''} placeholder="Optional" onChange={event=>update(set.id,{targetRpe:event.target.value===''?undefined:Number(event.target.value)})}/></Field></div></details>
   </li>})}</ol>
   <div className="row wrap planned-add-actions"><button type="button" className="secondary small" disabled={sets.length>=20} onClick={add}><Plus size={17}/>Add set</button><button type="button" className="textbtn" disabled={sets.length>=20} onClick={add}><Copy size={16}/>Duplicate previous set</button></div><small className="muted">New sets copy the previous set’s targets and notes.</small>
   <Field label="Exercise notes (optional)"><textarea rows={2} maxLength={EXERCISE_NOTES_LIMIT} aria-label={`${e.name} exercise notes`} value={e.notes||''} placeholder="Cues for this planned exercise" onChange={event=>onChange({notes:event.target.value})}/></Field>
   <details className="planned-group"><summary>Superset relationship (optional)</summary><p className="muted">Keep related exercises together. Each exercise is logged separately.</p><div className="planned-metadata"><Field label="Superset group"><input maxLength={120} aria-label={`${e.name} superset group`} value={e.groupId||''} placeholder="For example: A" onChange={event=>onChange({groupId:event.target.value||undefined,groupType:event.target.value?'SUPERSET':undefined,groupOrder:event.target.value?e.groupOrder||1:undefined})}/></Field>{e.groupId&&<Field label="Position in group"><input type="number" min={1} max={30} step={1} aria-label={`${e.name} group order`} value={e.groupOrder||1} onChange={event=>onChange({groupOrder:Number(event.target.value)})}/></Field>}</div></details>
   {showError&&error&&<p className="editor-error" role="alert">{error}</p>}
   <div className="prescription-actions"><div className="row tight"><button type="button" className="iconbtn" aria-label={`Move ${e.name} up`} disabled={order===1} onClick={()=>onMove(-1)}><ChevronUp size={20}/></button><button type="button" className="iconbtn" aria-label={`Move ${e.name} down`} disabled={order===total} onClick={()=>onMove(1)}><ChevronDown size={20}/></button><button type="button" className="iconbtn danger" aria-label={`Remove ${e.name}`} onClick={onRemove}><Trash2 size={20}/></button></div><button type="button" className="secondary" onClick={()=>{setShowError(true);if(!error){onOpenChange(false);trigger.current?.focus()}}}>Done</button></div>
  </CollapsibleContent>
 </Collapsible>;
}
