"use client";
import {useEffect,useRef} from 'react';
import {CalendarDays,Check,ChevronLeft,ChevronRight,Dumbbell,Play,Plus,SkipForward} from 'lucide-react';
import {addDays,dateLabel,currentProgram,nextProgramWorkout,type State,type Log} from '@/lib/cadence';
import {prescriptionSummary} from '@/lib/prescription';
import PlannedExerciseDetails from './planned-exercise-details';
import {CycleStrip} from './training-controls';
import ScheduleOnboarding from './schedule-onboarding';
import HistoryWorkoutCard from './history-workout-card';

function nextWorkoutLabel(name:string){const label=`Next: ${name}`;return label.length>20?`${label.slice(0,19).trimEnd()}…`:label}

export default function ProgramSchedule({state:s,today,date,onDate,busy,run,onChoose,onCreate,onChangeWorkout,onSkipWorkout,onReview,onResume,mobile}:{state:State;today:string;date:string;onDate:(date:string)=>void;busy:boolean;run:(action:Record<string,unknown>)=>Promise<boolean>;onChoose:()=>void;onCreate:()=>void;onChangeWorkout:()=>void;onSkipWorkout:(name:string)=>void;onReview:(log:Log)=>void;onResume:()=>void;mobile:boolean}){
 const current=currentProgram(s,today),next=nextProgramWorkout(s,today),weekStart=addDays(date,-((new Date(date+'T12:00:00').getDay()+6)%7));
 const records=s.logs.filter(log=>log.date===date).sort((a,b)=>b.finishedAt.localeCompare(a.finishedAt)),session=s.session,skippedToday=current.schedule?.skippedWorkouts?.filter(skip=>skip.occurrence.date===today)||[],skippedDate=current.schedule?.skippedWorkouts?.filter(skip=>skip.occurrence.date===date)||[];
 const strip=useRef<HTMLDivElement>(null),revealToday=useRef(false);
 function backToToday(){revealToday.current=true;onDate(today)}
 useEffect(()=>{if(!revealToday.current||date!==today)return;revealToday.current=false;const container=strip.current,day=container?.querySelector<HTMLElement>('[aria-current=date]');if(container&&day&&container.scrollWidth>container.clientWidth)container.scrollTo({left:day.offsetLeft-container.offsetLeft-(container.clientWidth-day.offsetWidth)/2,behavior:'instant'})},[date,today]);
 return <>
  {!current.schedule&&<ScheduleOnboarding mobile={mobile} onChoose={onChoose} onCreate={onCreate}/>}
  <section className={'panel calendar'+(!current.schedule?' calendar-empty':'')}><div className="row between"><div><h3>{dateLabel(date,{month:'long',year:'numeric'})}</h3><p className="muted">Your training history</p></div><div className="row tight calendar-controls"><button type="button" className="iconbtn" aria-label="Previous week" onClick={()=>onDate(addDays(date,-7))}><ChevronLeft/></button>{date!==today&&<button type="button" className="secondary small calendar-today-return" onClick={backToToday}>Back to Today</button>}<button type="button" className="iconbtn" aria-label="Next week" disabled={addDays(weekStart,7)>today} onClick={()=>onDate(addDays(date,7)>today?today:addDays(date,7))}><ChevronRight/></button><input className="datejump" aria-label="Jump to date" type="date" max={today} value={date} onChange={e=>{if(e.target.value&&e.target.value<=today)onDate(e.target.value)}}/></div></div>
   <div className="week" ref={strip}>{Array.from({length:7},(_,i)=>{const d=addDays(weekStart,i),logs=s.logs.filter(log=>log.date===d),skips=s.schedules.flatMap(schedule=>schedule.skippedWorkouts||[]).filter(skip=>skip.occurrence.date===d),inProgress=d===today&&!!session,recorded=logs.length>0;return <button type="button" className={(d===date?'selected ':'')+(d===today?'istoday':'')} key={d} disabled={d>today} onClick={()=>onDate(d)} aria-pressed={d===date} aria-current={d===today?'date':undefined} aria-label={`${d===today?'Today · ':''}${dateLabel(d,{weekday:'long',month:'long',day:'numeric'})}${recorded?` · ${logs.length} recorded workout${logs.length===1?'':'s'}`:''}${skips.length?` · ${skips.length} skipped workout${skips.length===1?'':'s'}`:''}${!recorded&&!skips.length&&inProgress?' · Workout in progress':''}`}><span className="weekday">{dateLabel(d,{weekday:'short'})}</span><b>{Number(d.slice(-2))}</b><span className={'daymark '+(recorded?'complete':'')}>{recorded?<><Check size={14}/>{skips.length>0&&<SkipForward size={12}/>}</>:skips.length?<SkipForward size={14}/>:inProgress?<Dumbbell size={14}/>:<span>—</span>}</span><span className={'dayname'+(recorded?' day-workout-count':'')} aria-hidden="true">{recorded?<><Dumbbell size={12}/><span>{logs.length>99?'99+':logs.length}</span>{skips.length>0&&<SkipForward size={12}/>}</>:skips.length?'Skipped':inProgress?'Active':'—'}</span></button>})}</div>
  </section>
  <div className="schedulegrid"><div>
   {date===today&&(next||session)?<section className="panel daydetail"><div className="row between"><p className="eyebrow">TODAY</p><span className={'status '+(session?'in_progress':'planned')+(next&&!session?' next-workout-status':'')} aria-label={next&&!session?`Next workout: ${next.day.name}`:undefined} title={next&&!session?`Next workout: ${next.day.name}`:undefined}>{session?'In progress':next?nextWorkoutLabel(next.day.name):'Next workout'}</span></div><h2>{session?.name||next?.day.name}</h2><p className="muted">{next&&(!session||session.occurrence)?`Workout ${(current.cursor?.index||0)+1} of ${current.workouts.length} · Cycle ${current.cursor?.cycleNumber} · ${next.programName} · Version ${next.versionNumber}`:'Unscheduled workout'}</p>{session?<button type="button" className="primary schedule-next-action" disabled={busy} onClick={onResume}><Play size={18}/>Resume workout</button>:next&&<><p className="muted cycle-pace-note">Your next workout stays here until you finish it. Rest whenever you need.</p>{skippedToday.map(skip=><p className="skipped-workout-note" key={skip.occurrence.id}><SkipForward size={16}/>Skipped this cycle: {skip.occurrence.day.name}</p>)}<div className="row wrap cycle-position-actions"><button type="button" className="secondary small" disabled={busy} onClick={onChangeWorkout}>Change workout</button><button type="button" className="textbtn small skip-workout-action" disabled={busy} onClick={()=>onSkipWorkout(next.day.name)}><SkipForward size={16}/>Skip workout</button></div>{next.day.notes&&<p className="planned-workout-notes">{next.day.notes}</p>}<div className="planlist">{next.day.exercises.map((exercise,i)=><div key={exercise.id}><span className="exnumber">{i+1}</span><div><b>{exercise.name}</b><p className="muted">{prescriptionSummary(exercise,s.settings.unit)}</p>{exercise.notes&&<p className="muted planned-exercise-notes">{exercise.notes}</p>}<PlannedExerciseDetails exercise={exercise} unit={s.settings.unit}/></div></div>)}</div><button type="button" className="primary schedule-next-action" disabled={busy} onClick={()=>run({type:'startWorkout',date:today})}><Play size={18}/>Start workout · {next.day.name}</button></>}</section>:date<today&&!records.length&&!skippedDate.length?<section className="panel daydetail"><p className="eyebrow">{dateLabel(date,{weekday:'long',month:'long',day:'numeric'})}</p><h2>No workout recorded</h2><p className="muted">Rest days don’t change your program progress.</p></section>:null}
   {skippedDate.length>0&&date<today&&<section className="panel recorded-workouts skipped-workouts"><h3>Skipped workouts</h3><div>{skippedDate.map(skip=><p key={skip.occurrence.id}><SkipForward size={16}/>{skip.occurrence.day.name} · Cycle {skip.occurrence.cycleNumber}</p>)}</div></section>}{records.length>0&&<section className="panel recorded-workouts"><h3>{date===today?'Today’s workouts':dateLabel(date,{weekday:'long',month:'long',day:'numeric'})}</h3><div className="history-list">{records.map(log=><HistoryWorkoutCard key={log.id} state={s} log={log} onOpen={()=>onReview(log)}/>)}</div></section>}
   {date===today&&!session&&<button type="button" className="textbtn extra-workout" disabled={busy} onClick={()=>run({type:'startWorkout',date:today,unscheduled:true})}><Plus size={17}/>Start unscheduled workout</button>}
  </div><aside>{current.schedule&&<section className="panel"><p className="eyebrow">YOUR CYCLE</p><h3>{current.program?.name}</h3><CycleStrip days={current.workouts} activeIndex={current.cursor?.index}/><p className="muted footnote">Finish a workout to move to the next. Rest days don’t advance the cycle.</p></section>}{current.cursor?.queued&&<section className="panel pending"><p className="eyebrow">NEXT VERSION</p><h3>Version {s.programs.find(p=>p.id===current.cursor?.queued?.programId)?.versions.find(v=>v.id===current.cursor?.queued?.versionId)?.number}</h3><p className="muted">Applies after current cycle</p></section>}<section className="panel recent-workouts-list"><p className="eyebrow">RECENT WORKOUTS</p>{s.logs.length?s.logs.slice().sort((a,b)=>b.finishedAt.localeCompare(a.finishedAt)).map(log=><button type="button" className="recentlog" key={log.id} onClick={()=>onReview(log)}><div><b>{log.name}</b><p className="muted">{dateLabel(log.date)}</p></div><Check size={18}/></button>):<p className="muted">Your finished workouts will appear here.</p>}</section></aside></div>
 </>;
}
