import {updateRestForSets,actualSetErrors,plannedWorkStatus} from './workout-rules';
import {prescriptionError,normalizePlan} from './prescription';
import { State, BodyMetricLog, Program, CycleDay, ActualExercise, Session, PlanExercise, Occurrence, exerciseLibrary, CYCLE_LENGTHS, uid, clone, activeSchedule, getVersion, projection, completion, actualFromPlan, dayNumber, ensureCycleState, currentProgram, nextProgramWorkout, advanceProgram, activateProgramVersion, workoutDays } from './cadence';
export class RuleError extends Error{constructor(message:string,public code='INVALID',public details:unknown=null){super(message)}}
const assert=(condition:unknown,message:string,code?:string,details?:unknown)=>{if(!condition)throw new RuleError(message,code,details)};
function validDate(d:unknown):asserts d is string{assert(typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(dayNumber(d))&&new Date(dayNumber(d)*86400000).toISOString().slice(0,10)===d,'Choose a valid calendar date.')}
function num(n:unknown,min:number,max:number,integer=false){assert(typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max&&(!integer||Number.isInteger(n)),`Enter a number from ${min} to ${max}.`)}
function text(t:unknown,max=120){assert(typeof t==='string'&&t.trim().length>0&&t.length<=max,'Enter a valid name.');return (t as string).trim()}
function metadata(value:unknown,max=120){if(value===undefined)return '';assert(typeof value==='string'&&value.length<=max,'Enter valid exercise metadata.');return (value as string).trim()}
function validateDays(days:CycleDay[],state:State){assert(Array.isArray(days)&&CYCLE_LENGTHS.some(length=>length===days.length),'Choose a cycle of 1 to 12 workouts.');assert(days.some(d=>d.type==='WORKOUT'),'Add at least one workout day.');for(const d of days){assert(['REST','WORKOUT'].includes(d.type),'Choose workout or rest for every day.');if(d.type==='REST'){d.name='Rest';d.exercises=[];continue}d.name=text(d.name);assert(d.notes===undefined||typeof d.notes==='string'&&d.notes.length<=4000,'Workout notes must be at most 4000 characters.');assert(Array.isArray(d.exercises)&&d.exercises.length>0&&d.exercises.length<=30,'Add exercises to every workout day.');for(const e of d.exercises){const item=exerciseLibrary(state,true).find(x=>x.id===e.exerciseId);assert(item,'Choose an exercise from the catalog.');e.name=item!.name;e.id=e.id||uid();const error=prescriptionError(e);assert(!error,error)}assert(new Set(d.exercises.map(e=>e.id)).size===d.exercises.length,'Exercises need unique IDs.');d.exercises=d.exercises.map((e,i)=>normalizePlan(e,i+1,state.settings.unit))}}
function setValidation(exercises:ActualExercise[],original:ActualExercise[]){assert(Array.isArray(exercises)&&exercises.length===original.length,'Exercise structure does not match the saved workout.');for(const e of exercises){const old=original.find(x=>x.id===e.id);assert(old,'Exercise no longer exists.');assert(JSON.stringify(e.planned)===JSON.stringify(old!.planned)&&e.exerciseId===old!.exerciseId&&e.name===old!.name,'Exercise plans must stay unchanged.');assert(new Set(e.sets.map(set=>set.id)).size===e.sets.length,'Set IDs must remain unique.');assert(e.sets.every((set,i)=>set.id===old!.sets[i].id),'Set order must remain unchanged.');assert(e.sets.length===old!.sets.length,'Use Add set to change workout structure.');assert(typeof e.skipped==='boolean'&&e.skipped===old!.skipped,'Use Skip exercise to change skip status.');for(const set of e.sets){const previous=old!.sets.find(x=>x.id===set.id);assert(previous&&previous.planned===set.planned&&previous.prescriptionId===set.prescriptionId,'Planned set obligations must remain unchanged.');assert(typeof set.done==='boolean'&&!!set.skipped===!!previous!.skipped,'Invalid set state.');assert(!set.done||!set.skipped,'Restore skipped sets before completing them.');const errors=actualSetErrors(set);assert(!errors.weight,errors.weight||'Invalid weight.');assert(!errors.reps,errors.reps||'Invalid reps.')}}}
export function act(s:State,input:any,today:string,timezone:string):State{
 validDate(today);assert(input&&typeof input.type==='string','Invalid action.');ensureCycleState(s,today);const now=new Date().toISOString();
 const session=()=>{assert(s.session,'No active workout.');return s.session!};
 switch(input.type){
 case 'saveProgram':{const name=text(input.name);assert(Array.isArray(input.days),'Add workouts to your cycle.');const days=clone(input.days).filter((day:CycleDay)=>day.type!=='REST');validateDays(days,s);const p=s.programs.find(x=>x.id===input.id);if(p){assert(!p.preset,'Choose a preset to save your own editable copy.');assert(!p.archived,'Restore this program before editing.');const active=currentProgram(s,today),inUse=active.application?.programId===p.id||active.cursor?.queued?.programId===p.id;if(inUse){const versionId=active.cursor?.queued?.programId===p.id?active.cursor.queued.versionId:p.versions.at(-1)?.id,existing=getVersion(s,p.id,versionId).version,oldNames=existing&&workoutDays(existing.days).map((day:CycleDay)=>day.name),newNames=days.map((day:CycleDay)=>day.name),sameNames=oldNames&&oldNames.length===newNames.length&&[...oldNames].sort().join('\u0000')===[...newNames].sort().join('\u0000');assert(!(sameNames&&oldNames!.some((day:string,index:number)=>day!==newNames[index])),'Workout order cannot be changed while this program is in use.')}p.name=name;p.description=String(input.description||'').slice(0,500);p.versions.push({id:uid(),number:p.versions.length+1,days,createdAt:now});delete p.needsCycleSetup}else{s.programs.push({id:uid(),name,description:String(input.description||'').slice(0,500),archived:false,versions:[{id:uid(),number:1,days,createdAt:now}]})}break}
 case 'renameProgram':{const p=s.programs.find(x=>x.id===input.id);assert(p,'Program not found.');assert(!p!.preset,'Presets cannot be renamed.');p!.name=text(input.name);p!.description=String(input.description||'').slice(0,500);break}
 case 'duplicateProgram':{const p=s.programs.find(x=>x.id===input.id);assert(p,'Program not found.');const copy=clone(p!);copy.id=uid();copy.name=p!.preset?p!.name:`${p!.name} (copy)`;copy.archived=false;delete copy.preset;delete copy.needsCycleSetup;copy.versions=[{...clone(p!.versions.at(-1)!),id:uid(),number:1,createdAt:now}];copy.versions[0].days=workoutDays(copy.versions[0].days);delete copy.versions[0].templateOnly;s.programs.push(copy);break}
 case 'archiveProgram':{const p=s.programs.find(x=>x.id===input.id);assert(p,'Program not found.');assert(!p!.preset,'Presets cannot be archived.');const current=currentProgram(s,today);assert(!input.archived||(current.application?.programId!==p!.id&&current.cursor?.queued?.programId!==p!.id),'Switch or stop the active program and cancel its queued version before archiving.');p!.archived=!!input.archived;break}
 case 'createSchedule':{assert(!activeSchedule(s),'Stop the current program first.');assert(!s.session,'Finish or discard the active workout first.');const {program,version}=getVersion(s,input.programId,input.versionId),workouts=version&&workoutDays(version.days);assert(program&&!program.archived&&version&&workouts?.length,'Choose an available program version.');const index=input.startIndex??0;assert(Number.isInteger(index)&&index>=0&&index<workouts!.length,'Choose a valid starting workout.');const app={id:uid(),programId:program!.id,versionId:version!.id,effective:today,suppressed:[]};s.schedules.push({id:uid(),start:today,end:null,status:'ACTIVE',applications:[app],overrides:[],cycleState:{appId:app.id,index,cycleNumber:1,queued:null},skippedWorkouts:[]});break}
 case 'applyVersion':{const {schedule,cursor,application}=currentProgram(s,today);assert(schedule&&cursor,'Start a program first.');assert(input.mode==='NOW'||input.mode==='AFTER_CYCLE','Choose Apply now or Apply after current cycle.');const {program,version}=getVersion(s,input.programId,input.versionId),workouts=version&&workoutDays(version.days);assert(program&&!program.archived&&version&&workouts?.length,'Choose a valid program version.');const index=input.startIndex??0;assert(Number.isInteger(index)&&index>=0&&index<workouts!.length,'Choose a valid starting workout.');assert(!cursor!.queued,'Cancel the queued version change first.');assert(application?.versionId!==version!.id||application.programId!==program!.id,'This version is already active.');if(input.mode==='NOW'){assert(!s.session,'Finish or discard the active workout before applying a version now.');activateProgramVersion(s,program!.id,version!.id,today,index)}else cursor!.queued={programId:program!.id,versionId:version!.id,index};break}
 case 'changeWorkout':{const {schedule,cursor,version}=currentProgram(s,today),workouts=version&&workoutDays(version.days);assert(schedule&&cursor&&workouts?.length,'Start a program first.');assert(!s.session,'Finish or discard the current workout before changing it.');assert(Number.isInteger(input.index)&&input.index>=0&&input.index<workouts!.length,'Choose a valid workout.');const occurrence=nextProgramWorkout(s,today);assert(occurrence?.day.type==='WORKOUT','There is no planned workout to change.');assert(!(schedule!.skippedWorkouts||[]).some(skip=>skip.occurrence.appId===cursor!.appId&&skip.occurrence.cycleNumber===cursor!.cycleNumber&&skip.occurrence.id===`${schedule!.id}:${cursor!.appId}:cycle:${cursor!.cycleNumber}:workout:${input.index}`),'That workout was already skipped in this cycle.');cursor!.index=input.index;break}
 case 'skipWorkout':{const {schedule,cursor}=currentProgram(s,today),occurrence=nextProgramWorkout(s,today);assert(schedule&&cursor&&occurrence,'There is no planned workout to skip.');assert(!s.session,'Finish or discard the current workout before skipping it.');assert(input.confirmed===true,'Confirm before skipping the workout.');schedule!.skippedWorkouts??=[];assert(!schedule!.skippedWorkouts.some(skip=>skip.occurrence.id===occurrence!.id),'This workout is already skipped.');schedule!.skippedWorkouts.push({occurrence:clone(occurrence!),skippedAt:now});advanceProgram(s,occurrence!,today);break}
 case 'cancelFuture':{const {cursor}=currentProgram(s,today);assert(cursor?.queued,'No queued version change.');cursor!.queued=null;break}
 case 'endSchedule':{const sch=activeSchedule(s);assert(sch,'No active schedule.');assert(input.confirmed===true,'Confirm before ending the schedule.');assert(!s.session||input.stopActiveWorkout===true,'Confirm stopping the active workout with this program.');if(today>=sch!.start){validDate(input.date);assert(input.date>=today&&input.date>=sch!.start,'End date cannot rewrite previous dates.')}if(s.session){const sess=s.session;setValidation(sess.exercises,sess.exercises);s.logs.push({...clone(sess),finishedAt:now,timerSource:null,timerId:null,status:sess.occurrence?(completion(sess.exercises)?'COMPLETED':'PARTIALLY_COMPLETED'):'UNSCHEDULED',timerEnd:null});s.session=null}if(today<sch!.start){sch!.status='CANCELLED';sch!.end=null}else{sch!.status='ENDED';sch!.end=input.date}break}
 case 'override':{assert(false,'Workouts follow your program cycle. Calendar moves and swaps are no longer supported.');break}
 case 'replaceOccurrence':{assert(false,'Change the active program version to change the workout cycle.');break}
 case 'startWorkout':{assert(!s.session,'Resume, finish, or discard the active workout first.');validDate(input.date);assert(input.date===today,'Start workouts from Today. Past dates show recorded history only.');const o=input.unscheduled?null:nextProgramWorkout(s,today);if(!input.unscheduled)assert(o?.day.type==='WORKOUT','Choose an active program.');s.session={id:uid(),date:today,name:o?.day.name||'Unscheduled Workout',startedAt:now,timezone,occurrence:clone(o),exercises:o?o.day.exercises.map(actualFromPlan):[],notes:'',timerEnd:null};break}
 case 'saveSession':{const sess=session();assert(input.id===sess.id,'This workout changed in another tab.');setValidation(input.exercises,sess.exercises);updateRestForSets(sess,input.exercises,s.settings.defaultRest);sess.exercises=clone(input.exercises);sess.notes=String(input.notes||'').slice(0,4000);sess.name=text(input.name);break}
 case 'addSet':{const sess=session();const e=sess.exercises.find(e=>e.id===input.exerciseId);assert(e&&!e.skipped,'Select an active exercise.');assert(e!.sets.length<40,'Maximum 40 sets per exercise.');e!.sets.push({id:uid(),planned:false,reps:null,weight:null,done:false});break}
 case 'removeSet':{const e=session().exercises.find(e=>e.id===input.exerciseId),set=e?.sets.find(set=>set.id===input.setId);assert(e&&set&&!set.planned,'Only extra sets can be removed.');assert(!set!.done,'Uncheck a completed extra set before removing it.');e!.sets=e!.sets.filter(set=>set.id!==input.setId);break}
 case 'addExercise':{const sess=session();const item=exerciseLibrary(s).find(e=>e.id===input.exerciseId);assert(item,'Choose a catalog exercise.');assert(sess.exercises.length<40,'Maximum 40 exercises.');sess.exercises.push({id:uid(),planned:null,name:item!.name,exerciseId:item!.id,skipped:false,sets:[{id:uid(),planned:false,reps:null,weight:null,done:false}]});break}
 case 'substitute':{const sess=session();const e=sess.exercises.find(e=>e.id===input.id),item=exerciseLibrary(s).find(e=>e.id===input.exerciseId);assert(e&&item,'Choose a valid replacement exercise.');assert(!e!.sets.some(x=>x.done),'Substitute before recording completed sets.');e!.exerciseId=item!.id;e!.name=item!.name;e!.skipped=false;for(const set of e!.sets)set.skipped=false;if(sess.timerSource?.exerciseId===e!.id){sess.timerEnd=null;sess.timerId=null;sess.timerSource=null}break}
 case 'skipExercise':{const sess=session(),e=sess.exercises.find(e=>e.id===input.id);assert(e,'Exercise not found.');if(input.skipped){assert(e!.sets.some(set=>!set.done),'No remaining sets to skip.');assert(!e!.sets.some(set=>set.done)||input.confirmRemaining===true,'Confirm skipping remaining sets.')}e!.skipped=!!input.skipped;for(const set of e!.sets){if(!set.done)set.skipped=!!input.skipped}sess.timerEnd=null;sess.timerId=null;sess.timerSource=null;break}
 case 'removeExtra':{const sess=session();const e=sess.exercises.find(e=>e.id===input.id);assert(e&&!e.planned,'Planned exercises can be skipped, not removed.');sess.exercises=sess.exercises.filter(x=>x.id!==input.id);if(sess.timerSource?.exerciseId===input.id){sess.timerEnd=null;sess.timerId=null;sess.timerSource=null}break}
 case 'timer':{const sess=session();if(input.extend===30||input.adjust===15||input.adjust===-15){assert(sess.timerEnd!==null,'Start rest before adjusting it.');sess.timerEnd=Math.max(Date.now(),Math.max(Date.now(),sess.timerEnd!)+(input.extend===30?30000:input.adjust*1000))}else if(input.seconds===null){sess.timerEnd=null;sess.timerId=null;sess.timerSource=null}else{num(input.seconds,1,600,true);sess.timerEnd=Date.now()+input.seconds*1000;sess.timerId=uid();sess.timerSource=null}break}
 case 'finishWorkout':{const sess=session();const complete=completion(sess.exercises);assert(!sess.occurrence||plannedWorkStatus(sess.exercises).pending===0||input.confirmIncomplete===true,'Confirm finishing while planned sets are still pending.','INCOMPLETE');assert(sess.occurrence||sess.exercises.some(e=>e.sets.some(x=>x.done)),'Complete at least one set before finishing an unscheduled workout.');s.logs.push({...clone(sess),finishedAt:now,timerSource:null,timerId:null,status:sess.occurrence?(complete?'COMPLETED':'PARTIALLY_COMPLETED'):'UNSCHEDULED',timerEnd:null});advanceProgram(s,sess.occurrence,today);s.session=null;break}
 case 'discardWorkout':{session();assert(input.confirmed===true,'Confirm before discarding the workout.');s.session=null;break}
 case 'deleteLog':{assert(input.confirmed===true,'Confirm before deleting the workout.');assert(typeof input.id==='string'&&s.logs.some(log=>log.id===input.id),'Workout log not found.');s.logs=s.logs.filter(log=>log.id!==input.id);break}
 case 'correctLog':{const log=s.logs.find(l=>l.id===input.id);assert(log,'Workout log not found.');assert(input.confirmed===true,'Confirm historical corrections.');setValidation(input.exercises,log!.exercises);log!.exercises=clone(input.exercises);log!.notes=String(input.notes||'').slice(0,4000);log!.status=log!.occurrence?(completion(log!.exercises)?'COMPLETED':'PARTIALLY_COMPLETED'):'UNSCHEDULED';assert(log!.occurrence||log!.exercises.some(e=>e.sets.some(x=>x.done)),'An unscheduled log must retain at least one completed set.');log!.correctedAt=now;break}
 case 'createCustomExercise':{s.customExercises??=[];const name=text(input.name);assert(!exerciseLibrary(s).some(e=>e.name.toLowerCase()===name.toLowerCase()),'An exercise with this name already exists.');s.customExercises.push({id:'custom-'+uid(),source:'USER',name,muscle:metadata(input.muscle),equipment:metadata(input.equipment),notes:metadata(input.notes,4000),archived:false});break}
 case 'editCustomExercise':{const e=s.customExercises?.find(e=>e.id===input.id&&e.source==='USER');assert(e,'Only your custom exercises can be edited.');const name=text(input.name);assert(!exerciseLibrary(s).some(other=>other.id!==e!.id&&other.name.toLowerCase()===name.toLowerCase()),'An exercise with this name already exists.');Object.assign(e!,{name,muscle:metadata(input.muscle),equipment:metadata(input.equipment),notes:metadata(input.notes,4000)});break}
 case 'archiveCustomExercise':{const e=s.customExercises?.find(e=>e.id===input.id&&e.source==='USER');assert(e,'Only your custom exercises can be archived.');assert(typeof input.archived==='boolean','Choose archive or restore.');e!.archived=input.archived;break}
 case 'settings':{assert(['kg','lb'].includes(input.unit),'Choose kg or lb.');num(input.defaultRest,0,3600,true);const lengthUnit=['cm','in'].includes(input.lengthUnit)?input.lengthUnit:(s.settings?.lengthUnit||'cm');s.settings={unit:input.unit,defaultRest:input.defaultRest,lengthUnit};break}
  case 'logBodyMetric':{
   assert(input&&typeof input==='object','Enter valid body metric data.');
   const weight=Number(input.weight);
   assert(Number.isFinite(weight)&&weight>0&&weight<1000,'Enter a valid body weight.');
   const id=(typeof input.id==='string'&&input.id.trim())?input.id.trim():uid();
   const timestamp=(typeof input.timestamp==='string'&&input.timestamp.trim())?input.timestamp.trim():now;
   const metric:BodyMetricLog={id,timestamp,weight:Math.round(weight*100)/100};
   if(typeof input.note==='string'&&input.note.trim())metric.note=input.note.trim().slice(0,150);
   const optNum=(val:unknown,min:number,max:number)=>{
    if(val===undefined||val===null||val==='')return undefined;
    const n=Number(val);
    assert(Number.isFinite(n)&&n>=min&&n<=max,`Measurement must be between ${min} and ${max}.`);
    return Math.round(n*100)/100;
   };
   const bf=optNum(input.bodyFatPercentage,1,99);if(bf!==undefined)metric.bodyFatPercentage=bf;
   const mm=optNum(input.muscleMass,1,500);if(mm!==undefined)metric.muscleMass=mm;
   const upperKeys=['neck','shoulders','chest','leftArm','rightArm','leftForearm','rightForearm'] as const;
   for(const k of upperKeys){const val=optNum(input[k],1,500);if(val!==undefined)metric[k]=val;}
   const lowerKeys=['waist','abdomen','hips','leftThigh','rightThigh','leftCalf','rightCalf'] as const;
   for(const k of lowerKeys){const val=optNum(input[k],1,500);if(val!==undefined)metric[k]=val;}
   s.bodyMetrics??=[];
   const existingIdx=s.bodyMetrics.findIndex(m=>m.id===id);
   if(existingIdx>=0)s.bodyMetrics[existingIdx]=metric;
   else s.bodyMetrics.push(metric);
   s.bodyMetrics.sort((a,b)=>b.timestamp.localeCompare(a.timestamp));
   break;
  }
  case 'deleteBodyMetric':{
   assert(input.confirmed===true,'Confirm before deleting this entry.');
   assert(typeof input.id==='string','Metric ID required.');
   s.bodyMetrics??=[];
   s.bodyMetrics=s.bodyMetrics.filter(m=>m.id!==input.id);
   break;
  }
 default:throw new RuleError('Unknown action.');
 }
 return s;
}

